import type { HowToBody } from "../types.js";

export const CP09: Record<string, HowToBody> = {
  "apply-security-template": {
    summary: "Import a secedit .inf baseline for password, lockout, and audit options.",
    what: "Runs secedit /configure against a local .inf (default config/windows/cp-baseline.inf) covering password length/history/lockout, Success+Failure audit, and a few security-option registry values. LGPO-style baselines belong here too. Local image only.",
    whyItScores:
      "Public Windows kits apply a security template in one shot so password policy, Guest, and audit policy are not forgotten under the clock. This is that mutate, with dryRun and confirm.",
    whenToRun: "Windows auth pass after you have read the README. Prefer dryRun first.",
    steps: [
      "Open config/windows/cp-baseline.inf and confirm min length, lockout, and Guest=0 match this image’s README.",
      "Run with dryRun:true. The result should name the template and not call secedit for real.",
      "Live mode requires confirm:true. Re-run audit-password-policy and enable-audit-policy’s categories should now look set.",
      "If a README-required service breaks, stop and revert from your snapshot — do not import a template you have not read.",
    ],
    goodLooksLike: [
      "Password min length ≥14, history, lockout, Guest disabled.",
      "Audit policy Success+Failure on logon/account management.",
    ],
    risks: [
      "Mutation. Live requires confirm:true (or dryRun:true to preview).",
      "secedit overwrites local policy. Snapshot the image first.",
      "Authorized-image only. Never pointed at another team.",
    ],
    related: ["audit-password-policy", "enable-audit-policy", "enforce-password-policy", "disable-guest-account"],
    keywords: ["secedit", "inf", "LGPO", "secpol", "cp-baseline.inf", "confirm"],
  },
  "import-firewall-profile": {
    summary: "Import a .wfw export or apply a known-good local firewall profile.",
    what: "If you pass a netsh .wfw path, it is imported. Otherwise Domain/Private/Public are enabled with default-deny inbound and allow outbound — the same known-good stance as apply-default-deny-inbound.",
    whyItScores: "Windows Firewall off or allow-all inbound is a staple finding. Importing a known-good profile is how many public kits do it in one click.",
    whenToRun: "After audit-firewall, once you know which inbound ports the README requires (then add those rules separately).",
    steps: [
      "Run audit-firewall / list-firewall-rules so you know current profile state.",
      "dryRun:true to see whether a .wfw would be imported or the known-good profile applied.",
      "Live confirm:true. Re-run audit-firewall — profiles should be on, inbound Block.",
      "If the README requires a listener (80/443/22), add an allow rule after default-deny — do not leave inbound Allow.",
    ],
    goodLooksLike: [
      "All profiles Enabled, DefaultInboundAction Block, outbound Allow.",
      "README-required ports still reachable on the image.",
    ],
    risks: [
      "Mutation. Live requires confirm:true.",
      "A leftover .wfw from another image can be wrong — prefer the known-good apply unless you exported this image yourself.",
    ],
    related: ["audit-firewall", "enable-firewall", "apply-default-deny-inbound", "list-firewall-rules"],
    keywords: ["wfw", "netsh advfirewall import", "DefaultInboundAction", "confirm"],
  },
  "enable-audit-policy": {
    summary: "Turn on Success+Failure auditing for the key Windows categories.",
    what: "Calls auditpol for Account Logon, Account Management, Logon/Logoff, Policy Change, Privilege Use, and System — Success and Failure. Writes the local Security log; it does not dump that log here.",
    whyItScores: "‘Audit policy not configured’ is a common Windows scoring item and you want those events for your own forensics notes.",
    whenToRun: "Windows logging pass with audit-logging, after apply-security-template or instead of it if you only need auditpol.",
    steps: [
      "Run with dryRun:true to see the six categories.",
      "Live confirm:true.",
      "Do not export or upload the Security log off-image.",
    ],
    goodLooksLike: ["Those six categories show Success and Failure.", "Security log is enabled, contents not dumped by this op."],
    risks: [
      "Mutation. Live requires confirm:true.",
      "This is not a remote audit and not a CCS query.",
    ],
    related: ["audit-logging", "apply-security-template", "audit-powershell-logging", "export-evidence-bundle"],
    keywords: ["auditpol", "Success and Failure", "Account Logon", "confirm"],
  },
  "disable-remote-registry": {
    summary: "Stop and disable the RemoteRegistry service.",
    what: "Stops RemoteRegistry and sets startup Disabled. Workstations do not need remote hive access.",
    whyItScores: "Remote Registry is a frequent CP plant and a scoring item even when RDP stays.",
    whenToRun: "Windows services pass with disable-rdp and disable-remote-assistance.",
    steps: [
      "Confirm the README does not require Remote Registry (it almost never does).",
      "dryRun:true, then live confirm:true.",
      "Re-run list-services / flag-risky-services — RemoteRegistry should be stopped/disabled.",
    ],
    goodLooksLike: [
      "RemoteRegistry Stopped, StartupType Disabled.",
      "list-services no longer shows RemoteRegistry as running.",
    ],
    risks: [
      "Mutation. Live requires confirm:true.",
      "Do not confuse this with disabling the whole Remote Desktop stack — that is disable-rdp.",
    ],
    related: ["flag-risky-services", "disable-rdp", "disable-remote-assistance", "disable-service"],
    keywords: ["RemoteRegistry", "remote registry", "confirm"],
  },
  "disable-remote-assistance": {
    summary: "Turn off Remote Assistance offer/full-control on the local image.",
    what: "Sets fAllowToGetHelp=0 and fAllowFullControl=0 under HKLM Remote Assistance. Complements disable-rdp; does not touch other hosts.",
    whyItScores: "Remote Assistance is a separate Windows scoring checkbox from RDP and is almost never authorized.",
    whenToRun: "With disable-rdp and disable-remote-registry.",
    steps: [
      "Read the README. If a help-desk Remote Assistance item is required (rare), stop.",
      "dryRun:true, then live confirm:true.",
      "System Properties → Remote should show Remote Assistance unchecked.",
    ],
    goodLooksLike: ["fAllowToGetHelp=0.", "RDP handled separately via disable-rdp if the README does not need it."],
    risks: [
      "Mutation. Live requires confirm:true.",
      "This is not an attack against another team’s Remote Assistance.",
    ],
    related: ["disable-rdp", "audit-rdp", "disable-remote-registry", "hunt-remote-access-tools"],
    keywords: ["fAllowToGetHelp", "Remote Assistance", "msra", "confirm"],
  },
  "force-password-change": {
    summary: "Expire passwords so authorized users must change at next logon (bulk or one name).",
    what: "chage -d 0 or net user /logonpasswordchg:yes. Pass username for one account; omit it to bulk-expire humans on allowed-users.txt (root/Administrator skipped in bulk). Deepens expire-user-password. Never invents or prints passwords.",
    whyItScores: "README users often still have the default password. Forcing a change is the kosher way to rotate without embedding a new password in the tool.",
    whenToRun: "After sync-authorized-users and enforce-password-policy, before you walk away from the account pane.",
    steps: [
      "Put the README humans in config/allowed-users.txt.",
      "dryRun:true with no username to see the bulk list, or with username for one account.",
      "Live confirm:true. Then log on as that user (or tell the teammate) to set a strong password — this op will not set one for you.",
      "Do not expire a service account. Skip names the README says must keep a known password for a scored service.",
    ],
    goodLooksLike: [
      "Authorized humans must change password at next logon.",
      "Output has no password values — only names.",
    ],
    risks: [
      "Mutation. Live requires confirm:true.",
      "Bulk mode skips root/Administrator so you are not locked out of the console account.",
      "Never invents passwords and never prints them.",
    ],
    related: ["expire-user-password", "enforce-password-policy", "sync-authorized-users", "check-password-aging"],
    keywords: ["chage -d 0", "logonpasswordchg", "bulk expire", "confirm"],
  },
  "sync-authorized-users": {
    summary: "Create missing README users (no passwords invented) and flag extras.",
    what: "Reads config/allowed-users.txt and config/allowed-admins.txt. Creates missing humans without a password and lists setPasswordManually. Adds missing admins to sudo/Administrators. Extra interactive users and extra admins are flagged — not auto-disabled. Bend-parallel user sweep when available.",
    whyItScores:
      "Public kits sync users.txt/admins.txt at round start. Creating missing README users scores; planted extras must still be disabled by hand so you do not nuke a required account.",
    whenToRun: "Right after you paste the README lists into the two config files. Before disable-user.",
    steps: [
      "Copy the README user list into config/allowed-users.txt and admins into config/allowed-admins.txt (see also config/examples/).",
      "dryRun:true. Read missingToCreate, extras, extraAdmins, and setPasswordManually.",
      "Live confirm:true creates missing accounts with no password. Immediately set those passwords yourself (passwd / lusrmgr).",
      "Hand extras to disable-user / lock-user and extra admins to remove-user-from-admins — this op will not auto-disable them.",
    ],
    goodLooksLike: [
      "Every README human exists. New accounts have ‘set password manually’ and no password in the output.",
      "Extras are listed with remediation disable-user, not silently deleted.",
    ],
    risks: [
      "Mutation (creates/group-adds). Live requires confirm:true.",
      "Never invents passwords. Empty/locked new accounts cannot log in until you set one.",
      "Do not put passwords in the allowlist files.",
    ],
    related: ["select-unauthorized-users", "disable-user", "list-admin-users", "force-password-change"],
    keywords: ["allowed-users.txt", "allowed-admins.txt", "users.txt", "admins.txt", "set password manually", "confirm"],
  },
  "disable-optional-windows-features": {
    summary: "Bulk-disable Telnet, TFTP, SMB1 extras, SimpleTCP, and similar optional features.",
    what: "Disable-WindowsOptionalFeature -NoRestart for names in config/windows/optional-features.txt. Complements disable-telnet and disable-smbv1 when those features are still installed.",
    whyItScores: "Telnet Client, TFTP, Simple TCP, and SMB1 are classic leftover features on Windows images.",
    whenToRun: "Windows services/features pass after audit-ftp-telnet and audit-smb.",
    steps: [
      "Skim config/windows/optional-features.txt. Remove any name the README requires (IIS-FTP if FTP is scored).",
      "dryRun:true, then live confirm:true.",
      "Reboot later if DISM says so — this op does not reboot.",
    ],
    goodLooksLike: ["TelnetClient/TFTP/SMB1Protocol/SimpleTCP Disabled.", "NoRestart — you choose when to reboot."],
    risks: [
      "Mutation. Live requires confirm:true.",
      "Do not disable a README-required web/FTP feature. Edit the list first.",
    ],
    related: ["disable-telnet", "disable-smbv1", "audit-iis", "audit-ftp-telnet"],
    keywords: ["optional features", "TelnetClient", "TFTP", "SimpleTCP", "DISM", "confirm"],
  },
  "run-sfc-scan": {
    summary: "Read-only sfc /verifyonly report of Windows system-file integrity.",
    what: "Runs sfc /verifyonly and returns a truncated integrity report. It does not repair (that would be /scannow) and does not dump WinSxS payloads.",
    whyItScores: "Planted system files and a broken component store show up here. Knowing SFC is dirty tells you to snapshot and then repair on the image.",
    whenToRun: "When you suspect tampered system files, after audit-hosts-file, before a long update pass.",
    steps: [
      "Run the op. It can take several minutes on a real image.",
      "If violations name hosts or system DLLs, pair with clear-suspicious-hosts / apply-security-updates.",
      "Repair (sfc /scannow) is a separate admin action — this op stays read-only.",
    ],
    goodLooksLike: ["Windows Resource Protection did not find integrity violations.", "No WinSxS dump in the output."],
    risks: [
      "Read-only. Still slow — do not block the whole team on it at T+0.",
      "Authorized-image only.",
    ],
    related: ["audit-hosts-file", "apply-security-updates", "audit-critical-perm-drift", "enable-windows-defender"],
    keywords: ["sfc", "verifyonly", "system file checker", "integrity"],
  },
  "clear-suspicious-hosts": {
    summary: "Remove hosts-file sinkholes of Windows Update, AV, and public names.",
    what: "Rewrites /etc/hosts or drivers\\etc\\hosts dropping loopback/unspecified mappings for vendor and well-known names. Keeps localhost and the machine hostname. Complements audit-hosts-file.",
    whyItScores: "Blocking windowsupdate.microsoft.com in hosts is a classic plant that also stops patches and Defender signatures.",
    whenToRun: "Right after audit-hosts-file shows sinkholes, before apply-security-updates.",
    steps: [
      "Run audit-hosts-file. Note which names are pinned to 127.0.0.1 / 0.0.0.0.",
      "dryRun:true — wouldDrop should match those lines.",
      "Live confirm:true. Re-run audit-hosts-file. Then check-ntp / apply-security-updates.",
    ],
    goodLooksLike: [
      "Only localhost (and 127.0.1.1 hostname) remain.",
      "Windows Update / AV names resolve normally again.",
    ],
    risks: [
      "Mutation. Live requires confirm:true.",
      "If the README documents a required local hostname mapping, dryRun first so you do not drop it.",
    ],
    related: ["audit-hosts-file", "apply-security-updates", "enable-windows-defender", "check-ntp"],
    keywords: ["hosts file", "windowsupdate", "sinkhole", "0.0.0.0", "confirm"],
  },
  "disable-display-manager-guest": {
    summary: "Turn off LightDM/GDM guest sessions and autologin.",
    what: "Writes a LightDM drop-in (allow-guest=false, autologin-user empty) and sets GDM AutomaticLoginEnable=false. Distinct from disable-guest-account, which locks the Guest user.",
    whyItScores: "Ubuntu images often ship guest sessions and autologin. CAMS-style checklists call this out separately from the Guest account.",
    whenToRun: "Linux auth pass with disable-guest-account.",
    steps: [
      "dryRun:true to see current allow-guest / AutomaticLoginEnable.",
      "Live confirm:true.",
      "Also run disable-guest-account so the Guest user itself is off.",
    ],
    goodLooksLike: ["No guest session on the greeter.", "No autologin user."],
    risks: [
      "Mutation. Live requires confirm:true.",
      "If the README requires autologin for a kiosk account, stop — that is rare on CP.",
    ],
    related: ["disable-guest-account", "lock-root-account", "audit-idle-lock", "disable-user"],
    keywords: ["lightdm", "gdm", "allow-guest", "autologin", "confirm"],
  },
  "lock-root-account": {
    summary: "Lock the root password with passwd -l (UID 0 remains).",
    what: "passwd -l root so password auth as root fails. sudo can stay. Does not delete root or extra UID 0 accounts (use disable-user / audit-uid-zero for those).",
    whyItScores: "CAMS and Ubuntu checklists lock root so the only path is sudo for authorized admins.",
    whenToRun: "After you have a working sudo admin from allowed-admins.txt. Not before.",
    steps: [
      "Confirm alice (or another README admin) can sudo.",
      "dryRun:true, then live confirm:true.",
      "Do not lock root if the README requires a console root password — read it twice.",
    ],
    goodLooksLike: ["root still UID 0, password locked.", "sudo still works for allowed admins."],
    risks: [
      "Mutation. Live requires confirm:true.",
      "Locking root before you have sudo is a self-own. Check list-admin-users first.",
    ],
    related: ["lock-user", "disable-root-ssh", "list-admin-users", "audit-uid-zero"],
    keywords: ["passwd -l", "lock root", "usermod -L", "confirm"],
  },
  "enable-fail2ban": {
    summary: "Install the distro fail2ban package and enable the service.",
    what: "apt/dnf install fail2ban, then systemctl enable --now. If the package is not in the image’s repos, the op reports unavailable — it will not curl a random installer.",
    whyItScores: "SSH brute-force defense on the local image is a common Linux item. Missing universe repo should not panic you.",
    whenToRun: "After harden-sshd / disable-root-ssh, if the README does not forbid extra packages.",
    steps: [
      "dryRun:true to see whether fail2ban is already active.",
      "Live confirm:true. If apt/dnf cannot find the package, record that and move on.",
      "This jails local sshd. It is not a remote attack tool.",
    ],
    goodLooksLike: ["fail2ban.service active.", "Or a clear ‘package unavailable’ note — not a random GitHub install."],
    risks: [
      "Mutation (package install + enable). Live requires confirm:true.",
      "Do not fetch unofficial fail2ban installers. Do not point it at other teams.",
    ],
    related: ["harden-sshd", "disable-root-ssh", "enable-account-lockout", "audit-logging"],
    keywords: ["fail2ban", "ssh jail", "apt install", "confirm"],
  },
  "harden-host-conf": {
    summary: "Write /etc/host.conf with order hosts,bind and nospoof on.",
    what: "Replaces /etc/host.conf with the classic resolver hardening: order hosts,bind; multi on; nospoof on. Complements sysctl rp_filter.",
    whyItScores: "IP spoofing / hosts-bind order is a recurring Linux network checkbox in public kits.",
    whenToRun: "Linux network pass with harden-sysctl and clear-suspicious-hosts.",
    steps: [
      "dryRun:true to preview the file.",
      "Live confirm:true.",
      "Pair with harden-sysctl (rp_filter) rather than treating nospoof as the whole story.",
    ],
    goodLooksLike: [
      "/etc/host.conf contains nospoof on and order hosts,bind.",
      "multi on is present so the resolver still accepts multiple addresses.",
    ],
    risks: [
      "Mutation. Live requires confirm:true.",
      "nospoof is historical; still expected on many Ubuntu scoring images.",
    ],
    related: ["harden-sysctl", "audit-hosts-file", "clear-suspicious-hosts", "check-ntp"],
    keywords: ["host.conf", "nospoof", "order hosts,bind", "confirm"],
  },
  "set-ufw-logging": {
    summary: "Set UFW logging high and verify default deny incoming / allow outgoing.",
    what: "ufw logging high plus default deny incoming and allow outgoing. Does not open ports. If UFW is inactive, enable-firewall first.",
    whyItScores: "Default-deny plus high logging is the Linux firewall baseline public kits apply after ‘ufw enable’.",
    whenToRun: "Immediately after enable-firewall / apply-default-deny-inbound.",
    steps: [
      "If ufw is inactive, run enable-firewall first (confirm).",
      "dryRun:true, then live confirm:true on this op.",
      "ufw status verbose should show logging high and default deny incoming.",
    ],
    goodLooksLike: ["logging high", "Default: deny (incoming), allow (outgoing)"],
    risks: [
      "Mutation. Live requires confirm:true.",
      "Default deny can hide a README-required port — add an allow rule, do not flip default to allow.",
    ],
    related: ["enable-firewall", "apply-default-deny-inbound", "audit-firewall", "list-firewall-rules"],
    keywords: ["ufw logging high", "default deny incoming", "confirm"],
  },
  "restrict-cron-at": {
    summary: "Allow only root (and listed admins) to use crontab and at.",
    what: "Writes /etc/cron.allow and /etc/at.allow with root (plus allowed-admins) and removes cron.deny/at.deny. Existing root cron jobs stay. Complements audit-cron.",
    whyItScores: "World-usable cron/at is how plants persist. Restricting the scheduler to root is a CAMS staple.",
    whenToRun: "After audit-cron / audit-at-jobs, once you have copied any required user cron aside.",
    steps: [
      "Run audit-cron and snapshot any README-required user crontab.",
      "dryRun:true, then live confirm:true.",
      "Re-run audit-cron. Unauthorized users should no longer be able to crontab -e.",
    ],
    goodLooksLike: ["cron.allow and at.allow contain root.", "cron.deny/at.deny gone."],
    risks: [
      "Mutation. Live requires confirm:true.",
      "If a README user must have a crontab, add them to cron.allow after — do not leave deny-open.",
    ],
    related: ["audit-cron", "audit-at-jobs", "audit-persistence-deep", "sync-authorized-users"],
    keywords: ["cron.allow", "at.allow", "cron.deny", "confirm"],
  },
  "hunt-shell-backdoors": {
    summary: "Find alias hijacks and wget|sh plants in bashrc/profile (and PowerShell profiles).",
    what: "Read-only scan of /etc/profile, bashrc, profile.d, user rc files, and Windows PowerShell profiles for alias sudo=, nc -e, wget|sh, LD_PRELOAD, HISTFILE unset, and /tmp plants. Bend-parallel on Linux. Does not execute the rc files.",
    whyItScores: "A sudo alias or profile wget|sh is a persistence plant that survives user lock. Public kits grep these files; this op ranks the hits.",
    whenToRun: "Files pass with audit-persistence-deep and hunt-sysprep-leftovers.",
    steps: [
      "Run the op. Open each hit path on the image and snapshot before deleting the plant line.",
      "Do not bash -x the rc file — just edit out the plant.",
      "Re-run. Pair with audit-ssh-authorized-keys.",
    ],
    goodLooksLike: [
      "No alias sudo/ls/passwd in rc files.",
      "No wget|sh / DownloadString in profiles.",
    ],
    risks: [
      "Read-only. Deleting a line is a manual edit (or a later mutate).",
      "Do not execute untrusted rc files to ‘see what they do’.",
    ],
    related: ["audit-persistence-deep", "audit-ssh-authorized-keys", "find-backdoor-binaries", "audit-cron"],
    keywords: ["alias sudo", "bashrc", "profile.d", "HISTFILE", "wget|sh", "PowerShell profile"],
  },
  "scan-malware-tools": {
    summary: "Inventory clamav/chkrootkit; confirm may install distro packages then local-scan.",
    what: "dryRun reports whether clamscan/chkrootkit exist. With confirm:true the op may apt/dnf install the distro packages and scan /home /tmp /opt. No unofficial installers, no other hosts, no signature crawling off-image beyond the image’s configured repos.",
    whyItScores: "Some images award a local AV/rootkit scan. Many do not ship the packages — reporting ‘unavailable’ is correct; curling a random installer is not.",
    whenToRun: "Optional, after prohibited software and media. Do not block round-start on it.",
    steps: [
      "dryRun:true to see presence.",
      "If the README wants a scan and the package exists in apt/dnf, live confirm:true.",
      "If install fails, record unavailable and move on. Do not wget third-party bundles.",
    ],
    goodLooksLike: [
      "A local scan report, or a clear unavailable note.",
      "No hashes of unrelated files dumped wholesale.",
    ],
    risks: [
      "Mutation when installing. Live requires confirm:true; dryRun is inventory-only.",
      "Scans only local paths. Not a remote malware service.",
    ],
    related: ["find-prohibited-software", "find-backdoor-binaries", "hunt-remote-access-tools", "enable-windows-defender"],
    keywords: ["clamav", "chkrootkit", "clamscan", "confirm"],
  },
  "round-start-wizard": {
    summary: "Sequenced first-minutes guide: forensics → users → passwords → firewall → updates → prohibited software.",
    what: "Read-only checklist that points at existing ops in a sensible order. It does not run the mutate ops and does not contact the CCS. Use it as the one-click huddle at T+0.",
    whyItScores:
      "Other kits ship a giant .bat that does everything at once (and sometimes cheats). We sequence the legal work so the team does not forget forensics or the firewall while hunting SUID.",
    whenToRun: "First five minutes, and again whenever the huddle needs a next step.",
    steps: [
      "Run this op (demo or live read). Sort fail/warn first.",
      "Open each related op in order: skim-forensics-readme, sync-authorized-users, enforce-password-policy, enable-firewall, apply-security-updates, find-prohibited-software.",
      "Mutations still need confirm:true on those ops. Re-run the wizard; remaining fails should shrink.",
    ],
    goodLooksLike: [
      "Six sequenced rows, each with a related catalog id.",
      "ccsContacted is false.",
    ],
    risks: [
      "Read-only. It will not disable users or enable the firewall for you.",
      "Not the official scoreboard. Do not query scoring endpoints.",
    ],
    related: [
      "skim-forensics-readme",
      "sync-authorized-users",
      "enforce-password-policy",
      "enable-firewall",
      "one-click-hardening-checklist",
    ],
    keywords: ["round start", "wizard", "checklist", "users.txt", "one-click", "CCS"],
  },
};
