import type { HowToBody } from "../types.js";

export const CP10: Record<string, HowToBody> = {
  "harden-print-spooler": {
    summary: "Close PrintNightmare-class remote driver install and remote spooler RPC.",
    what: "Sets PointAndPrint RestrictDriverInstallationToAdministrators, turns off no-warning elevation, disables the remote spooler RPC endpoint, and requires RPC auth privacy. Leaves the local Spooler running unless the README says printing is unused.",
    whyItScores:
      "Remote printer driver install (PrintNightmare-class) is a staple Windows finding. Scoring wants remote print locked down even when a local printer stays.",
    whenToRun: "Windows services pass with disable-remote-registry and audit-smb, after you know whether printing is required.",
    steps: [
      "Confirm the README: is a local printer required? If yes, do not stop Spooler — only remote RPC.",
      "dryRun:true to see the PointAndPrint / RegisterSpoolerRemoteRpcEndPoint values.",
      "Live confirm:true. Re-run; remote RPC should be disabled and driver install restricted to Administrators.",
      "If printing is unused, separately disable-service Spooler (confirm) after this op.",
    ],
    goodLooksLike: [
      "RestrictDriverInstallationToAdministrators=1, NoWarningNoElevationOnInstall=0.",
      "RegisterSpoolerRemoteRpcEndPoint disabled. Local print still works if the README needs it.",
    ],
    risks: [
      "Mutation. Live requires confirm:true (or dryRun:true to preview).",
      "Do not stop Spooler on an image that scores a printer. Authorized-image only.",
    ],
    related: ["disable-service", "audit-smb", "disable-remote-registry", "flag-risky-services"],
    keywords: ["PrintNightmare", "PointAndPrint", "Spooler", "RegisterSpoolerRemoteRpcEndPoint", "confirm"],
  },
  "audit-lsa-protection": {
    summary: "Read RunAsPPL — whether LSA runs as a protected process.",
    what: "Reads HKLM LSA RunAsPPL / RunAsPPLBoot. Unprotected LSA is a credential-theft finding. Classification only — LSASS, hashes, and tickets are never dumped.",
    whyItScores: "Windows images often score LSA protection. Knowing the bit is on is the check; dumping LSASS is out of scope and against the rules.",
    whenToRun: "Windows auth extras with audit-uac and audit-credential-guard, after the high-value user/firewall work.",
    steps: [
      "Run the op. Note RunAsPPL=0 vs 1/2.",
      "If the README/image supports VBS, enabling RunAsPPL is a local policy action — this op is read-only.",
      "Never run a credential dump, mimikatz, or LSASS access tool. The result must not contain hashes.",
    ],
    goodLooksLike: ["RunAsPPL is 1 or 2 on images that score it.", "No hash or ticket material in the output."],
    risks: [
      "Read-only. Enabling RunAsPPL is a separate admin action after a README check.",
      "Do not dump LSASS. Authorized-image only.",
    ],
    related: ["audit-credential-guard", "audit-uac", "check-bitlocker-status", "audit-secure-boot"],
    keywords: ["RunAsPPL", "LSA", "Protected Process Light", "LSASS"],
  },
  "audit-credential-guard": {
    summary: "Report Credential Guard / Device Guard security services running.",
    what: "Reads Win32_DeviceGuard: Credential Guard, Configurable TCB, VBS status. Informational — some images score CG, others only want the state known. Isolated secrets are not dumped.",
    whyItScores: "VBS/Credential Guard is a Windows extras item on Server/Win10+ images that shipped with it. Knowing it is off tells you whether to enable it from the README.",
    whenToRun: "With audit-lsa-protection and audit-secure-boot. Skip enabling CG if the image cannot boot with VBS.",
    steps: [
      "Run the op. Note SecurityServicesRunning and VirtualizationBasedSecurityStatus.",
      "If CG is off and the README requires it, enable via local policy/msinfo — this op will not flip it.",
      "If the image is a VM without nested VBS, leave it off and document that.",
    ],
    goodLooksLike: ["Status matches the README.", "No isolated secret material in the result."],
    risks: [
      "Read-only. Forcing CG on a VM that cannot run VBS can brick the round — snapshot first.",
      "Authorized-image only. Not a remote attestation of other hosts.",
    ],
    related: ["audit-lsa-protection", "audit-secure-boot", "check-bitlocker-status", "audit-uac"],
    keywords: ["Credential Guard", "Device Guard", "VBS", "Win32_DeviceGuard"],
  },
  "audit-secure-boot": {
    summary: "Report Secure Boot on/off and Setup Mode — no firmware keys dumped.",
    what: "Calls Confirm-SecureBootUEFI. Off or Setup Mode is a firmware finding. PK/KEK/db material is never exported.",
    whyItScores: "Some Windows images score Secure Boot. Even when they do not, Setup Mode is a plant you want to know about.",
    whenToRun: "Windows extras after BitLocker/LSA, not in the first five minutes.",
    steps: [
      "Run the op. Note SecureBoot true/false.",
      "If the README requires Secure Boot and it is off, follow the image’s firmware procedure — this op will not enroll keys.",
      "Never copy PK/KEK material into chat, Git, or evidence zips.",
    ],
    goodLooksLike: ["Secure Boot on if the README requires it.", "No firmware key material in the result."],
    risks: [
      "Read-only. Firmware enroll is out of band and easy to get wrong under the clock.",
      "Authorized-image only.",
    ],
    related: ["check-bitlocker-status", "audit-lsa-protection", "audit-credential-guard", "run-sfc-scan"],
    keywords: ["Secure Boot", "UEFI", "SetupMode", "Confirm-SecureBootUEFI"],
  },
  "audit-wifi-profiles": {
    summary: "List saved SSIDs and auth types. Never prints Wi-Fi keys.",
    what: "Inventories netsh WLAN profiles: SSID + authentication only. Flags Open networks and leftover home/contest SSIDs. `key=clear` is never used.",
    whyItScores: "Leftover Open or home Wi-Fi profiles are a Windows extras item and a persistence/credential leak if keys were printed — we do not print them.",
    whenToRun: "Windows network pass with audit-dns-client and disable-llmnr-netbios-wpad.",
    steps: [
      "Run the op. Note Open vs WPA2 profiles.",
      "Delete leftover SSIDs on the image (`netsh wlan delete profile`) if they are not README-required. This op is read-only.",
      "Confirm the result has keyOmitted=true and no PSK/EAP password fields.",
    ],
    goodLooksLike: [
      "Only README-required SSIDs remain.",
      "No PSK, EAP password, or key=clear material in the output.",
    ],
    risks: [
      "Read-only. Do not run `netsh wlan show profile key=clear`.",
      "Do not put Wi-Fi keys in the coach packet or Git.",
    ],
    related: ["audit-dns-client", "disable-llmnr-netbios-wpad", "audit-hosts-file", "export-coach-packet"],
    keywords: ["wlan", "SSID", "Open network", "PSK omitted", "netsh wlan"],
  },
  "harden-powershell-constrained": {
    summary: "Turn on Script Block/Module logging and local transcription; optional Constrained Language.",
    what: "Enables the three PowerShell logging policies and writes transcripts under a local ProgramData path. Optional constrainedLanguage=true sets Constrained Language Mode. Deepens the read-only audit-powershell-logging.",
    whyItScores: "Script Block Logging off is a Windows logging finding and you want those events for your own notes. Transcription must stay on-image.",
    whenToRun: "Windows logging pass after audit-powershell-logging and enable-audit-policy.",
    steps: [
      "Run audit-powershell-logging so you know which of the three are off.",
      "dryRun:true, then live confirm:true. Leave constrainedLanguage false unless the README wants lock-down — it can break local admin scripts.",
      "Confirm the transcript directory is local (ProgramData), not a remote share.",
    ],
    goodLooksLike: [
      "Script Block Logging, Module Logging, and Transcription on.",
      "Transcript path is local. LanguageMode still FullLanguage unless you opted in.",
    ],
    risks: [
      "Mutation. Live requires confirm:true.",
      "Constrained Language can break this suite’s own PowerShell engine if you set it on the account you use to run ops. Default is logging only.",
      "Do not ship transcripts off-image.",
    ],
    related: ["audit-powershell-logging", "enable-audit-policy", "audit-logging", "export-evidence-bundle"],
    keywords: ["ScriptBlockLogging", "Transcription", "Constrained Language", "Module Logging", "confirm"],
  },
  "disable-smb-client-v1": {
    summary: "Turn off leftover SMBv1 *client* knobs after the server feature is gone.",
    what: "Sets EnableSMB1Protocol false on the SMB client, disables the SMB1Protocol optional feature if it remains, and stops mrxsmb10. Complements disable-smbv1 (server/feature) and disable-optional-windows-features.",
    whyItScores: "SMBv1 client leftovers still negotiate SMBv1 even when the server feature is off. Scoring and WannaCry-class exposure both care.",
    whenToRun: "Right after disable-smbv1 / disable-optional-windows-features on a Windows image.",
    steps: [
      "Run audit-smb so you know SMBv1 is actually still on the client.",
      "dryRun:true, then live confirm:true.",
      "Re-run audit-smb. SMBv2/3 can remain if shares are required.",
    ],
    goodLooksLike: ["EnableSMB1Protocol false on the client.", "mrxsmb10 stopped/disabled. SMBv2/3 may stay."],
    risks: [
      "Mutation. Live requires confirm:true.",
      "If a dinosaur README required SMBv1 (almost never), stop. Otherwise disable it. Does not scan other hosts.",
    ],
    related: ["disable-smbv1", "audit-smb", "disable-optional-windows-features", "enable-firewall"],
    keywords: ["SMBv1 client", "mrxsmb10", "EnableSMB1Protocol", "confirm"],
  },
  "audit-dns-client": {
    summary: "Read DNS servers and DoH on the local adapters — do not query those names.",
    what: "Lists DnsClientServerAddress, DoH, and NRPT. Flags 10.x/bogus servers. Complements audit-hosts-file (poisoning) without contacting those hosts.",
    whyItScores: "A planted DNS server or hosts sinkhole is how images break Windows Update and Defender. Seeing the adapter list is the check.",
    whenToRun: "Windows network pass with audit-hosts-file and clear-suspicious-hosts.",
    steps: [
      "Run the op. Note unexpected 10.x/RFC1918 DNS servers.",
      "If hosts-file poisoning is also present, run audit-hosts-file / clear-suspicious-hosts next.",
      "Do not nslookup the scoring server or other teams. Local config only.",
    ],
    goodLooksLike: [
      "DNS servers match the README or a normal ISP/AD resolver.",
      "No query was made to those names from this op.",
    ],
    risks: [
      "Read-only. Changing DNS is a separate admin action.",
      "Do not probe other hosts or the CCS. Authorized-image only.",
    ],
    related: ["audit-hosts-file", "clear-suspicious-hosts", "audit-wifi-profiles", "disable-llmnr-netbios-wpad"],
    keywords: ["DnsClient", "DoH", "NRPT", "DNS server"],
  },
  "audit-windows-roles": {
    summary: "Inventory DNS/DHCP/AD-DS presence on a Windows Server image — read-only suggestions.",
    what: "Lists installed ServerManager roles (or optional features on a workstation). Flags unexpected AD-DS, DNS, and DHCP on a member/workstation image. Does not promote, demote, or attack another DC.",
    whyItScores: "A workstation image with AD-DS/DNS/DHCP installed is usually a plant. Server images that *are* the DC need those roles left alone — read the README.",
    whenToRun: "Windows extras after you have read whether this image is a DC, member, or workstation.",
    steps: [
      "Read the README: is this a domain controller, member server, or workstation?",
      "Run the op. Unexpected AD/DNS/DHCP on a workstation is a remove-feature candidate (not this op).",
      "Never dcpromo / uninstall AD-DS on a README-required DC.",
    ],
    goodLooksLike: [
      "Role list matches the README.",
      "No domain demotion attempted by this op.",
    ],
    risks: [
      "Read-only. Uninstalling AD-DS is a separate, high-risk admin action.",
      "Do not target another team’s DC. Authorized-image only.",
    ],
    related: ["audit-iis", "list-services", "flag-risky-services", "disable-optional-windows-features"],
    keywords: ["WindowsFeature", "AD-DS", "DHCP", "DNS role", "dcpromo"],
  },
  "harden-null-session": {
    summary: "Set RestrictAnonymous / RestrictAnonymousSAM / RestrictNullSessAccess to the hardened baseline.",
    what: "Writes the four LSA/LanmanServer restrict values that audit-null-session only reads. Does not dump SAM, pipes, or hashes.",
    whyItScores: "Anonymous SAM / null session enumeration is a high Windows finding even when shares stay.",
    whenToRun: "After audit-null-session, with disable-remote-registry and audit-smb.",
    steps: [
      "Run audit-null-session so you know which values are 0.",
      "dryRun:true, then live confirm:true.",
      "Re-run audit-null-session. RestrictAnonymous and RestrictAnonymousSAM should be 1; EveryoneIncludesAnonymous 0.",
    ],
    goodLooksLike: [
      "RestrictAnonymous=1, RestrictAnonymousSAM=1, RestrictNullSessAccess=1, EveryoneIncludesAnonymous=0.",
      "No SAM dump in the output.",
    ],
    risks: [
      "Mutation. Live requires confirm:true.",
      "Do not dump SAM or hashes. Authorized-image only.",
    ],
    related: ["audit-null-session", "audit-smb", "disable-remote-registry", "audit-share-acls"],
    keywords: ["RestrictAnonymous", "RestrictAnonymousSAM", "RestrictNullSessAccess", "null session", "confirm"],
  },
  "blacklist-kernel-modules": {
    summary: "Blacklist uncommon protocols/filesystems; usb-storage only if you opt in.",
    what: "Writes /etc/modprobe.d/cp-blacklist.conf for dccp/sctp/cramfs/hfs/firewire and the list in config/kernel-module-blacklist.txt. usb-storage is included only when usbStorage=true (default false) so keyboards stay.",
    whyItScores: "Unused network filesystems and obscure protocols are CIS/CP extras. usb-storage is a README call because some images need a USB stick.",
    whenToRun: "Linux kernel pass with harden-sysctl, after you know whether removable storage is required.",
    steps: [
      "Skim config/kernel-module-blacklist.txt. Leave usbStorage false unless the README forbids USB disks.",
      "dryRun:true, then live confirm:true.",
      "Reboot is not required for the file to exist; loaded modules stay until rmmod/reboot.",
    ],
    goodLooksLike: [
      "/etc/modprobe.d/cp-blacklist.conf lists dccp/sctp/cramfs/hfs.",
      "usb-storage still loadable unless you passed usbStorage:true.",
    ],
    risks: [
      "Mutation. Live requires confirm:true.",
      "Blacklisting usb-storage can block a README-required USB workflow. Default is off.",
    ],
    related: ["harden-sysctl", "audit-sysctl", "harden-usb-storage", "audit-mac-enforcement"],
    keywords: ["modprobe.d", "blacklist", "dccp", "usb-storage", "confirm"],
  },
  "enforce-apparmor-profiles": {
    summary: "Move common AppArmor profiles from complain to enforce.",
    what: "Runs aa-enforce for apache2/mysqld/ntpd/named/dhcpd/ping/tcpdump when apparmor-utils is present. Complements audit-mac-enforcement (read). Does not setenforce SELinux.",
    whyItScores: "Permissive/complain MAC is a finding on images that shipped with profiles. Enforcing the stock profiles is the kosher fix.",
    whenToRun: "After audit-mac-enforcement, once you know AppArmor is the MAC on this image.",
    steps: [
      "Run audit-mac-enforcement. If SELinux is the MAC, stop — this op is AppArmor-only.",
      "dryRun:true, then live confirm:true.",
      "Re-run audit-mac-enforcement. Complain profiles for common daemons should drop.",
    ],
    goodLooksLike: ["aa-status shows apache2/mysqld/sshd in enforce if those packages exist.", "SELinux was not flipped."],
    risks: [
      "Mutation. Live requires confirm:true.",
      "Enforcing a broken profile can take down a README-required service — snapshot first.",
    ],
    related: ["audit-mac-enforcement", "audit-web-server", "harden-sshd", "audit-php-hardening"],
    keywords: ["aa-enforce", "AppArmor", "complain", "confirm"],
  },
  "enable-unattended-upgrades": {
    summary: "Write 20auto-upgrades and enable the distro unattended-upgrades package.",
    what: "Installs distro unattended-upgrades if missing and writes APT Periodic Update-Package-Lists 1 / Unattended-Upgrade 1. Complements audit-auto-updates. Does not fetch unofficial installers.",
    whyItScores: "Automatic security updates are a Linux scoring item and how you keep the image patched under the clock.",
    whenToRun: "After audit-auto-updates / check-pending-updates. Pair with apply-security-updates for the current backlog.",
    steps: [
      "Run audit-auto-updates so you know 20auto-upgrades is 0 or missing.",
      "dryRun:true, then live confirm:true. If apt cannot provide the package, the op reports that — do not wget a random installer.",
      "Re-run audit-auto-updates. Unattended-Upgrade should be 1.",
    ],
    goodLooksLike: [
      "/etc/apt/apt.conf.d/20auto-upgrades has Unattended-Upgrade 1.",
      "No GitHub/raw installer involved.",
    ],
    risks: [
      "Mutation. Live requires confirm:true.",
      "Need root/apt. Do not point at a third-party repo.",
    ],
    related: ["audit-auto-updates", "apply-security-updates", "check-pending-updates", "audit-hosts-file"],
    keywords: ["unattended-upgrades", "20auto-upgrades", "APT Periodic", "confirm"],
  },
  "audit-mail-services": {
    summary: "If postfix/exim/dovecot is installed, flag open relay and VRFY.",
    what: "Reads inet_interfaces, mynetworks, disable_vrfy_command, and Dovecot plaintext auth. Local config only — does not send mail or probe other MX hosts.",
    whyItScores: "An open relay or unused MTA is a high Linux finding. Knowing which knob is wrong tells you whether to harden or disable the daemon.",
    whenToRun: "Linux services pass with audit-web-server and audit-snmp, after flag-risky-services.",
    steps: [
      "Run the op. If mail is absent, you are done.",
      "Read the README: is mail a required service? If not, plan disable-service postfix/exim4.",
      "If mail stays, set mynetworks to local-only and disable_vrfy_command=yes on the image (this op is read-only).",
    ],
    goodLooksLike: [
      "No mynetworks 0.0.0.0/0. VRFY disabled. Or the MTA is not installed.",
      "This op did not send a test message.",
    ],
    risks: [
      "Read-only. Do not send mail to other hosts as a ‘test’.",
      "Authorized-image only.",
    ],
    related: ["flag-risky-services", "disable-service", "audit-web-server", "audit-snmp"],
    keywords: ["postfix", "mynetworks", "open relay", "VRFY", "dovecot"],
  },
  "audit-database-bind": {
    summary: "If MySQL/MariaDB/Postgres is installed, flag 0.0.0.0 bind and pg_hba trust.",
    what: "Reads bind-address / listen_addresses, skip-grant-tables, and pg_hba trust. Does not connect with credentials, dump user tables, or print passwords.",
    whyItScores: "A database listening on all interfaces or with trust-from-anywhere is a high LAMP finding. Querying mysql.user is unnecessary and can leak hashes.",
    whenToRun: "Linux LAMP pass with audit-web-server and audit-php-hardening.",
    steps: [
      "Run the op. If no DB is installed, you are done.",
      "README: is MySQL/Postgres required? If not, plan disable-service. If yes, bind to 127.0.0.1 and drop trust.",
      "Confirm the output has no passwords or SQL result sets.",
    ],
    goodLooksLike: [
      "bind-address 127.0.0.1 (or DB absent). No skip-grant-tables. No 0.0.0.0/0 trust.",
      "No SQL connections were made.",
    ],
    risks: [
      "Read-only. Do not mysql -u root without a password as an ‘exploit’ — that is still credential use; just fix the config.",
      "Authorized-image only. Do not scan other databases.",
    ],
    related: ["audit-php-hardening", "audit-web-server", "flag-risky-services", "disable-service"],
    keywords: ["bind-address", "skip-grant-tables", "pg_hba", "listen_addresses"],
  },
  "audit-php-hardening": {
    summary: "If PHP is present, flag expose_php, allow_url_include, and info.php.",
    what: "Reads php.ini knobs and inventories info.php/phpinfo.php by name under web roots. File contents are not dumped. disable_functions is reported as a list, not as an exploit recipe.",
    whyItScores: "expose_php and phpinfo pages leak versions; allow_url_include is a classic LAMP plant. Scoring wants those off on a required web server.",
    whenToRun: "With audit-web-server on a LAMP image.",
    steps: [
      "Run the op. Note expose_php, allow_url_include, and any info.php path.",
      "If the web server is required, edit php.ini on the image (this op is read-only) and remove info.php after you snapshot.",
      "Do not use dangerous functions as an attack path. The list is for disable_functions hardening.",
    ],
    goodLooksLike: [
      "expose_php=Off, allow_url_include=Off, no info.php in the web root — or PHP absent.",
      "info.php contents were not printed.",
    ],
    risks: [
      "Read-only. Deleting info.php is a separate file action after a forensics check.",
      "Not an exploit guide. Authorized-image only.",
    ],
    related: ["audit-web-server", "audit-database-bind", "find-hidden-executables", "audit-iis"],
    keywords: ["expose_php", "allow_url_include", "disable_functions", "info.php", "php.ini"],
  },
  "audit-snap-flatpak": {
    summary: "List snap/flatpak apps and flag games, remote-desktop, and leftovers.",
    what: "Runs snap list / flatpak list and flags steam, discord, anydesk, vlc, wine, and similar. Discovery only — this op does not uninstall.",
    whyItScores: "Unnecessary snaps/flatpaks are prohibited-software cousins on Ubuntu images. Knowing the name feeds remove-package.",
    whenToRun: "Linux packages pass with find-prohibited-software and hunt-remote-access-tools.",
    steps: [
      "Run the op. Note suspicious snap/flatpak names.",
      "Confirm they are not README-required, then remove-package (confirm) or `snap remove` on the image.",
      "core/snapd/gtk-common-themes are ignored on purpose.",
    ],
    goodLooksLike: [
      "No steam/discord/anydesk/vlc leftovers, or they are README-required.",
      "This op did not uninstall anything.",
    ],
    risks: [
      "Read-only. Removal is a mutate op with confirm:true.",
      "Do not remove snapd itself unless the README says so.",
    ],
    related: ["find-prohibited-software", "hunt-remote-access-tools", "remove-package", "remove-games-samples"],
    keywords: ["snap", "flatpak", "steam", "anydesk"],
  },
  "disable-ctrl-alt-del": {
    summary: "Mask ctrl-alt-del.target and extra serial gettys.",
    what: "Masks the CAD reboot target and disables serial-getty@ttyS0. Does not disable tty1–tty6 needed for local login.",
    whyItScores: "CAD reboot is a cheap plant on a physical/console image. Extra serial gettys are unused attack surface.",
    whenToRun: "Linux kernel extras with harden-sysctl, after you know a serial console is not required.",
    steps: [
      "Confirm the README does not require a serial console.",
      "dryRun:true, then live confirm:true.",
      "tty1–6 stay. CAD should no longer reboot.",
    ],
    goodLooksLike: [
      "systemctl status ctrl-alt-del.target is masked.",
      "Local tty login still works.",
    ],
    risks: [
      "Mutation. Live requires confirm:true.",
      "Do not mask getty@tty1. Authorized-image only.",
    ],
    related: ["harden-sysctl", "audit-idle-lock", "disable-display-manager-guest", "lock-root-account"],
    keywords: ["ctrl-alt-del", "CAD", "serial-getty", "confirm"],
  },
  "audit-ipv6-privacy": {
    summary: "Read IPv6 privacy/forwarding. Disable only with disableIPv6=true and confirm.",
    what: "Reads use_tempaddr, accept_ra, forwarding, disable_ipv6. Default is audit-only. disableIPv6=true writes sysctl to disable IPv6 and requires confirm:true (or dryRun).",
    whyItScores: "IPv6 forwarding/RA on a workstation is a sysctl cousin finding. Disabling IPv6 entirely is a README call — some images need it.",
    whenToRun: "Linux kernel pass with audit-sysctl. Leave disableIPv6 false unless the README forbids IPv6.",
    steps: [
      "Run with defaults (audit-only). Note accept_ra + forwarding.",
      "If the README says disable IPv6, re-run with disableIPv6:true dryRun:true, then confirm:true.",
      "If the README requires IPv6, do not disable — pair with harden-sysctl instead.",
    ],
    goodLooksLike: [
      "Privacy extensions on or IPv6 disabled, matching the README.",
      "Default run did not write sysctl.",
    ],
    risks: [
      "Default is read-only. Live disableIPv6 requires confirm:true.",
      "Disabling IPv6 can break dual-stack required services. Check the README.",
    ],
    related: ["harden-sysctl", "audit-sysctl", "blacklist-kernel-modules", "audit-firewall"],
    keywords: ["IPv6", "use_tempaddr", "accept_ra", "disable_ipv6", "confirm"],
  },
  "audit-log-persistence": {
    summary: "Check journald Storage=persistent and rsyslog actually running.",
    what: "Reads journald.conf Storage, /var/log/journal presence, and rsyslog active state. Complements audit-logging: this is persistence, not just ‘is a daemon installed’.",
    whyItScores: "Volatile journald loses forensics evidence across reboot. Scoring and your own write-ups both need logs that stick.",
    whenToRun: "Linux logging pass with audit-logging and check-auditd.",
    steps: [
      "Run the op. Storage=volatile or missing /var/log/journal is the finding.",
      "Set Storage=persistent in journald.conf on the image (this op is read-only) and mkdir /var/log/journal.",
      "Do not ship logs off-image or to the CCS.",
    ],
    goodLooksLike: [
      "journald Storage=persistent (or /var/log/journal present) and rsyslog active.",
      "Logs were not exported off-image.",
    ],
    risks: [
      "Read-only. Editing journald.conf is a separate action.",
      "Do not upload the journal to a coach laptop that is not the authorized image.",
    ],
    related: ["audit-logging", "check-auditd", "export-evidence-bundle", "export-coach-packet"],
    keywords: ["journald", "Storage=persistent", "rsyslog", "/var/log/journal"],
  },
  "audit-browser-policy": {
    summary: "Deepen browser baseline: homepage, proxy, and extension ids (no cookies).",
    what: "Reads Firefox/Chrome/Edge/IE homepage, proxy/PAC, and extension directory *ids*. Cookies, history, saved passwords, and extension source are never dumped. Complements audit-browser-baseline and hunt-remote-access-tools.",
    whyItScores: "A planted homepage or system proxy to a contest box is a common extras item and how images phone home. Extension ids tell you what to remove without copying payloads.",
    whenToRun: "With audit-browser-baseline and hunt-remote-access-tools, after users/firewall.",
    steps: [
      "Run the op. Note unexpected homepages (10.x, pwn) and system proxies.",
      "Fix policies.json / IE settings on the image (this op is read-only). Remove leftover extension directories after a snapshot.",
      "Confirm cookies and passwords are absent from the result.",
    ],
    goodLooksLike: [
      "Homepage is about:blank or a README page. No 10.x proxy.",
      "Extension ids listed without source. No cookies/passwords.",
    ],
    risks: [
      "Read-only. Do not dump cookies or saved passwords into the coach packet.",
      "Authorized-image only.",
    ],
    related: ["audit-browser-baseline", "hunt-remote-access-tools", "audit-hosts-file", "export-coach-packet"],
    keywords: ["homepage", "proxy", "PAC", "extension id", "policies.json"],
  },
  "harden-usb-storage": {
    summary: "Disable USB autorun/execute. Mass-storage driver stays unless you opt in.",
    what: "Windows: NoDriveTypeAutoRun and RemovableStorageDevices Deny_Execute. Linux: udev/udisks automount off. Optional disableUsbStorage=true blacklists usb-storage/USBSTOR — default false so keyboards/mice stay. Deepens disable-autoplay.",
    whyItScores: "Autorun from removable media is a persistence path and a checkbox Windows/Linux item. Killing the USB HID stack is usually wrong.",
    whenToRun: "With disable-autoplay on Windows, or Linux kernel extras after blacklist-kernel-modules.",
    steps: [
      "Leave disableUsbStorage false unless the README forbids USB disks.",
      "dryRun:true, then live confirm:true.",
      "Removable media should not auto-launch. Keyboard still works.",
    ],
    goodLooksLike: [
      "Autorun/automount off. Deny_Execute on removable (Windows).",
      "USBSTOR/usb-storage still loaded unless you opted in.",
    ],
    risks: [
      "Mutation. Live requires confirm:true.",
      "disableUsbStorage=true can block a README-required USB stick and, on some images, more than disks. Default is off.",
    ],
    related: ["disable-autoplay", "blacklist-kernel-modules", "enable-windows-defender", "audit-startup-items"],
    keywords: ["NoDriveTypeAutoRun", "usb-storage", "automount", "Deny_Execute", "confirm"],
  },
  "audit-time-timezone": {
    summary: "Deepen NTP: timezone sanity and fake 10.x time sources.",
    what: "Reads timedatectl/w32time plus /etc/timezone or tzutil, and NTP server lists. Flags RFC1918/planted servers and bizarre Etc/GMT+ offsets. Complements check-ntp. Not an NTP amplification test and not a CCS query.",
    whyItScores: "Wrong clocks break logs, Kerberos, and TLS. A planted NTP server is how images stay unsynced on purpose.",
    whenToRun: "With check-ntp on both platforms, early enough that later logs have the right time.",
    steps: [
      "Run the op. Note timezone vs the README (usually US/Eastern or the site’s zone) and NTP servers.",
      "If NTP is 10.x/planted, point timesyncd/chrony/w32time at a normal pool or the README’s server — this op is read-only.",
      "Do not run NTP flood tests. Do not query the CCS for the time.",
    ],
    goodLooksLike: [
      "Clock NTP-synchronized. Timezone matches the README.",
      "No 10.x NTP server unless the README says so.",
    ],
    risks: [
      "Read-only. Changing timezone/NTP is a separate admin action.",
      "Not an amplification test. Authorized-image only. CCS is not contacted.",
    ],
    related: ["check-ntp", "audit-logging", "audit-dns-client", "scoreboard-preflight"],
    keywords: ["timedatectl", "timezone", "NTP", "w32tm", "chrony"],
  },
  "export-coach-packet": {
    summary: "Redacted ZIP for coach handoff: summaries and inventories, no secrets.",
    what: "Writes SUMMARY.md, findings.json, and user/service/port inventories (hashes omitted) into a local ZIP. Distinct from export-evidence-bundle: this is the coach-facing packet. Never includes shadow/SAM, private keys, Wi-Fi PSKs, cookies, or CCS URLs.",
    whyItScores:
      "Coaches want a clean handoff without secrets. Scoring does not want you to exfiltrate the image. This is Sabbath-coffee maximalism still inside the rules.",
    whenToRun: "End of a pass or when a coach asks for status. After the high-value mutates, not instead of them.",
    steps: [
      "Run the op. Optional outputDir must be a local path (never a URL or UNC).",
      "Open SUMMARY.md on the image. Confirm hashesIncluded=false, wifiKeysIncluded=false, ccsContacted=false.",
      "Hand the ZIP to a coach on a USB stick from the authorized image if the rules allow — do not email secrets.",
    ],
    goodLooksLike: [
      "ZIP contains SUMMARY.md + inventories. redacted=true.",
      "No hashes, PSKs, cookies, or CCS URLs.",
    ],
    risks: [
      "Read-only assembly. Still do not copy shadow, SAM, or Wi-Fi keys into the packet — the engine will not.",
      "Not off-image exfiltration. Not a CCS scrape. Authorized-image only.",
    ],
    related: ["export-evidence-bundle", "package-forensics-evidence", "scoreboard-preflight", "round-start-wizard"],
    keywords: ["coach packet", "ZIP", "redacted", "handoff", "CCS"],
  },
};
