/**
 * Dashboard shell (cp-01) still uses dotted ids (`users.list`).
 * Catalog / engines use kebab ids (`list-users`). Map the closest explainer
 * so OpPanel “How to” opens a real catalog guide.
 */
export const DASHBOARD_TO_CATALOG: Readonly<Record<string, string>> = Object.freeze({
  "users.list": "list-users",
  "users.flag-suspicious": "flag-suspicious-users",
  "users.disable": "disable-user",
  "users.enable": "lock-user",
  "users.delete": "disable-user",
  "users.groups": "list-groups",
  "users.uid0": "audit-uid-zero",
  "users.guest-audit": "disable-guest-account",
  "users.password-aging": "check-password-aging",
  "users.empty-password": "check-empty-passwords",
  "auth.password-policy": "audit-password-policy",
  "auth.failed-logins": "enable-account-lockout",
  "auth.ssh-harden": "ssh-hardening-audit",
  "auth.sudoers": "audit-sudoers",
  "auth.sessions": "list-users",
  "svc.running": "list-services",
  "svc.insecure": "flag-risky-services",
  "svc.processes": "find-backdoor-binaries",
  "svc.startup": "audit-startup-items",
  "svc.cron": "audit-cron",
  "net.ports": "audit-listening-ports",
  "net.firewall-status": "audit-firewall",
  "net.firewall-apply": "apply-default-deny-inbound",
  "net.shares": "audit-shared-folders",
  "net.hosts": "audit-hosts-file",
  "fs.world-writable": "find-world-writable",
  "fs.suid": "find-suid-sgid",
  "fs.sticky": "audit-home-permissions",
  "fs.home-perms": "audit-home-permissions",
  "fs.prohibited-media": "find-media-files",
  "fs.web-hidden": "find-hidden-executables",
  "fs.integrity": "check-sensitive-file-perms",
  "log.service": "audit-logging",
  "log.sudo": "audit-sudoers",
  "log.auth-spike": "enable-account-lockout",
  "log.notepad": "export-evidence-bundle",
  "sw.inventory": "list-installed-packages",
  "sw.prohibited": "find-prohibited-software",
  "sw.updates": "check-pending-updates",
  "sw.remote-access": "flag-risky-services",
  "win.registry": "disable-autoplay",
  "win.secpol": "audit-password-policy",
  "win.iis": "list-services",
  "win.powershell": "audit-powershell-logging",
  "linux.pam": "audit-pam",
  "linux.authorized-keys": "audit-ssh-authorized-keys",
  "linux.modules": "audit-startup-items",
  "linux.mac": "audit-sysctl",
  "team.preflight": "one-click-hardening-checklist",
  "team.journal": "export-evidence-bundle",
  "team.export": "export-evidence-bundle",
  "team.favorites": "one-click-hardening-checklist",
});
