import type { OpDefinition } from "./types.js";
import {
  allowlistParams,
  expectedPortsParams,
  firewallProfileParams,
  forcePasswordChangeParams,
  forensicsSkimParams,
  gamesSamplesParams,
  mutateFlagParams,
  op,
  optionalFeaturesParams,
  packageParams,
  securityTemplateParams,
  syncUsersParams,
  usernameDryRunParams,
} from "./schema.js";

const KOSHER =
  " Authorized-image hardening only: never used against other teams, scoring endpoints, or off-image hosts.";

export const catalog: readonly OpDefinition[] = Object.freeze([
  op(
    "list-users",
    "List local users",
    "users",
    "both",
    "read",
    "Enumerate local accounts with UID/GID or SID, home/profile, shell, group membership, lock state, and last-login timestamp. Password hashes are never returned." +
      KOSHER,
    "15 mixed Linux/Windows accounts including root, alice, toor (UID 0), hacker123, Guest, and service accounts",
  ),
  op(
    "flag-suspicious-users",
    "Flag suspicious users",
    "users",
    "both",
    "read",
    "Heuristic suspicion scoring for local accounts. Signals: never-logged-in humans, nonstandard shells, UID weirdness (non-root UID 0, duplicate UIDs, login shells on low UIDs), home outside /home, throwaway/backdoor name patterns, recently created accounts, and identities missing from config/allowed-users.txt. Admins not on the README allowlist score extra. This is a bulk audit with exportable reasons — not credential dumping and not an exploit. Use scores to prioritize lock/disable/remove-from-admin on the authorized image.",
    "Scored users: toor (UID 0), hacker123 (name+allowlist), zygote (shell/home/recent), nologin_admin (never logged in + sudo), Guest, flag; alice/bob/coach clean",
    allowlistParams,
  ),
  op(
    "disable-user",
    "Disable a local user",
    "users",
    "both",
    "mutate",
    "Disable an unauthorized local account (usermod/nologin or Disable-LocalUser). Live mode requires confirm:true. Does not delete home directories (forensics questions may need them).",
    "Simulates disabling hacker123; reports before/after lock and shell",
    usernameDryRunParams,
  ),
  op(
    "lock-user",
    "Lock a local user password",
    "users",
    "both",
    "mutate",
    "Lock the password of a local account (passwd -l / usermod -L or net user /active:no equivalent lock) so the account cannot authenticate, without destroying the account record. Live mode requires confirm:true.",
    "Simulates locking zygote; account remains listed but locked",
    usernameDryRunParams,
  ),
  op(
    "remove-user-from-admins",
    "Remove user from administrators",
    "users",
    "both",
    "mutate",
    "Drop a user from Administrators / sudo / wheel. Preferred over deletion when the README lists them as a standard user. Live mode requires confirm:true.",
    "Simulates removing nologin_admin from sudo while leaving the account enabled",
    usernameDryRunParams,
  ),
  op(
    "list-admin-users",
    "List administrators and sudoers",
    "users",
    "both",
    "read",
    "List members of Administrators, sudo, wheel, and UID 0. Cross-check against the README allowlist so extra admins are obvious.",
    "root, alice (expected sudo), nologin_admin (unexpected sudo), toor (UID 0), Administrator",
    allowlistParams,
  ),
  op(
    "audit-uid-zero",
    "Audit UID 0 accounts",
    "users",
    "linux",
    "read",
    "Find every passwd entry with UID 0. Only root should have UID 0 on a CyberPatriot Linux image. Extra UID 0 accounts are classic backdoors; flag them for disable.",
    "root (expected) and toor (duplicate UID 0, home /tmp/toor)",
  ),
  op(
    "check-empty-passwords",
    "Check for empty passwords",
    "users",
    "both",
    "read",
    "Detect accounts with empty or non-set passwords (shadow '!'/'!!'/empty, PasswordRequired=false). Never prints hashes — only a boolean empty/locked/set classification.",
    "Guest and games have empty/unusable-or-empty password flags; alice has a set password",
  ),
  op(
    "audit-never-logged-in",
    "Audit never-logged-in humans",
    "users",
    "both",
    "read",
    "Human/interactive accounts that have never logged in are often leftover or planted. Compare lastlog / LastLogon against the allowlist; service accounts with nologin are ignored.",
    "nologin_admin and flag never logged in; alice logged in recently",
  ),
  op(
    "check-user-shells",
    "Check login shells",
    "users",
    "linux",
    "read",
    "Report login shells. Interactive users should use a standard shell (bash/sh); system users should be nologin/false. Nonstandard shells (/tmp/*, interpreters, csh/zsh on a bash image, empty) are suspicious.",
    "zygote uses /usr/bin/python3; games uses /bin/bash despite being a system UID",
  ),
  op(
    "list-groups",
    "List local groups",
    "users",
    "both",
    "read",
    "Enumerate local groups and membership. Highlight privileged groups (sudo, wheel, Administrators, Hyper-V, Remote Desktop Users, docker).",
    "sudo (alice, nologin_admin), docker (zygote — unexpected), Administrators",
  ),
  op(
    "disable-guest-account",
    "Disable Guest account",
    "users",
    "both",
    "mutate",
    "Disable the Guest / guest account on Windows and Linux. Guest is almost never authorized on CP images. Live mode requires confirm:true.",
    "Simulates disabling Guest; account remains but enabled=false",
    mutateFlagParams,
  ),
  op(
    "audit-duplicate-uids",
    "Audit duplicate UIDs",
    "users",
    "linux",
    "read",
    "Find distinct usernames sharing a UID. Duplicate UID 0 is critical; other collisions still break auditing and privilege boundaries.",
    "toor shares UID 0 with root",
  ),
  op(
    "expire-user-password",
    "Expire a user password",
    "users",
    "both",
    "mutate",
    "Force a password change at next login (chage -d 0 / net user /logonpasswordchg:yes). Useful for authorized users with stale or known-default passwords. Live mode requires confirm:true.",
    "Simulates expiring bob's password without locking the account",
    usernameDryRunParams,
  ),
  op(
    "audit-password-policy",
    "Audit password policy",
    "auth",
    "both",
    "read",
    "Read /etc/login.defs + PAM pwquality/cracklib, or net accounts / secedit policy: min length, aging, history, complexity. Compare to typical CP baselines (length ≥12–14, history, max age).",
    "minlen 8 (too short), PASS_MAX_DAYS 99999, no complexity — several findings",
  ),
  op(
    "enforce-password-policy",
    "Enforce password policy",
    "auth",
    "both",
    "mutate",
    "Apply a conservative CP-friendly policy: min length 14, remember 5, max age 90, min age 1, complexity on, inactive lock. Does not change existing password hashes. Live requires confirm:true.",
    "Simulates writing login.defs/pwquality and a Windows net accounts policy",
    mutateFlagParams,
  ),
  op(
    "check-password-aging",
    "Check password aging",
    "auth",
    "linux",
    "read",
    "Parse chage/shadow aging fields (without hashes). Flag max days of -1/99999 on human accounts and users with aging disabled.",
    "bob MAX_DAYS=99999; alice 90; root aging disabled",
  ),
  op(
    "audit-pam",
    "Audit PAM configuration",
    "auth",
    "linux",
    "read",
    "Inspect common-auth / system-auth for pam_pwquality, pam_tally2/faillock, pam_unix remember, and nullok. nullok is a high finding; missing faillock is medium.",
    "common-auth still has nullok; no faillock; pwquality missing",
  ),
  op(
    "enable-account-lockout",
    "Enable account lockout",
    "auth",
    "both",
    "mutate",
    "Enable PAM faillock or Windows lockout policy after repeated failures (deny=5, unlock_time=600). Stops password-guessing on the local image only. Live mode requires confirm:true.",
    "Simulates enabling faillock and net accounts /lockoutthreshold:5",
    mutateFlagParams,
  ),
  op(
    "disable-root-ssh",
    "Disable SSH root login",
    "auth",
    "linux",
    "mutate",
    "Set PermitRootLogin no in sshd_config and reload ssh if it is a required service. Live requires confirm:true.",
    "Simulates PermitRootLogin yes → no with a config diff snippet",
    mutateFlagParams,
  ),
  op(
    "audit-sudoers",
    "Audit sudoers",
    "auth",
    "linux",
    "read",
    "Read /etc/sudoers and sudoers.d for NOPASSWD, ALL=(ALL) ALL granted to unexpected users, and world-writable sudoers files. Does not execute sudo commands as other users.",
    "nologin_admin ALL=(ALL) NOPASSWD: ALL; /etc/sudoers.d/hack world-writable",
  ),
  op(
    "audit-uac",
    "Audit User Account Control",
    "auth",
    "windows",
    "read",
    "Read EnableLUA, ConsentPromptBehaviorAdmin, and PromptOnSecureDesktop. UAC disabled is a high finding on a Windows CP image.",
    "EnableLUA=0 (UAC off), ConsentPromptBehaviorAdmin=0",
  ),
  op(
    "list-services",
    "List services",
    "services",
    "both",
    "read",
    "List systemd/Windows services with active/enabled state. Annotate against config/required-services.txt and config/risky-services.txt.",
    "sshd (required, running), telnet (enabled — bad), cups, avahi, smbd, apache2, mysql",
  ),
  op(
    "flag-risky-services",
    "Flag risky services",
    "services",
    "both",
    "read",
    "Cross-check running/enabled services against the risky list and required list. Telnet, rsh, anonymous FTP, SMBv1, RemoteRegistry, and similar score high unless the README explicitly requires them. Bulk audit, not an exploit scan of other hosts.",
    "telnet, vsftpd, smbd, cups, avahi, RemoteRegistry flagged; sshd/apache2 required",
  ),
  op(
    "disable-service",
    "Disable a service",
    "services",
    "both",
    "mutate",
    "Stop and disable a local service (systemctl disable --now / Set-Service -StartupType Disabled). Live requires confirm:true. Will refuse to disable names in required-services.txt unless forced.",
    "Simulates disabling telnet.socket and vsftpd",
    {
      type: "object",
      properties: {
        service: { type: "string", description: "Service/unit name" },
        dryRun: { type: "boolean", default: false, description: "Describe only" },
        force: {
          type: "boolean",
          default: false,
          description: "Allow disabling a service listed as required",
        },
      },
      required: ["service"],
    },
  ),
  op(
    "audit-ftp-telnet",
    "Audit FTP and Telnet",
    "services",
    "both",
    "read",
    "Detect telnet/ftp servers, sockets, and listening 21/23. Anonymous FTP and Telnet are almost never kosher on CP images.",
    "telnet.socket enabled, vsftpd running with anonymous_enable=YES, port 23 open",
  ),
  op(
    "disable-telnet",
    "Disable Telnet",
    "services",
    "both",
    "mutate",
    "Disable telnetd / TlntSvr / telnet.socket and block tcp/23 on the host firewall. Live requires confirm:true.",
    "Simulates stopping telnet and adding a deny-23 firewall rule",
    mutateFlagParams,
  ),
  op(
    "disable-legacy-r-services",
    "Disable rsh/rlogin/rexec",
    "services",
    "linux",
    "mutate",
    "Disable rsh, rlogin, rexec, and related xinetd entries. These trust-based remotes have no place on a CP image. Live mode requires confirm:true.",
    "Simulates disabling rsh.socket rlogin.socket rexec.socket",
    mutateFlagParams,
  ),
  op(
    "audit-smb",
    "Audit SMB / Samba",
    "services",
    "both",
    "read",
    "Report smbd/nmbd/LanmanServer state, guest/anonymous access, SMBv1, and share list. Guest shares and SMBv1 are high findings unless the README requires file sharing.",
    "smbd running, map to guest, SMBv1 enabled, public share with Everyone Full",
  ),
  op(
    "audit-listening-ports",
    "Audit listening ports",
    "ports",
    "both",
    "read",
    "List TCP/UDP listeners (ss/Get-NetTCPConnection) bound on this image. Flag 23, 111, 139, 445, 512-514, 5900, 31337, 4444, and anything bound to 0.0.0.0 that is not a required service. Local audit only — does not scan other hosts.",
    "22/80 expected; 23, 445, 31337/nc, 4444 flagged",
  ),
  op(
    "ssh-hardening-audit",
    "SSH hardening audit",
    "network",
    "linux",
    "read",
    "Parse sshd_config: PermitRootLogin, PasswordAuthentication, Protocol, X11Forwarding, MaxAuthTries, PermitEmptyPasswords, Ciphers/MACs, AllowUsers. Read-only; does not connect outbound.",
    "PermitRootLogin yes, PermitEmptyPasswords yes, Protocol 2+1, X11Forwarding yes",
  ),
  op(
    "harden-sshd",
    "Harden sshd_config",
    "network",
    "linux",
    "mutate",
    "Write a conservative sshd drop-in: PermitRootLogin no, PermitEmptyPasswords no, X11Forwarding no, MaxAuthTries 4, Protocol 2. Reloads sshd. Live requires confirm:true.",
    "Simulates a drop-in at /etc/ssh/sshd_config.d/99-cp-hardening.conf",
    mutateFlagParams,
  ),
  op(
    "audit-rdp",
    "Audit Remote Desktop",
    "network",
    "windows",
    "read",
    "Check fDenyTSConnections, NLA, and TermService. RDP should be off unless the README requires it; NLA should be on if RDP stays.",
    "RDP enabled, NLA off, TermService running",
  ),
  op(
    "disable-rdp",
    "Disable Remote Desktop",
    "network",
    "windows",
    "mutate",
    "Set fDenyTSConnections=1 and stop TermService if RDP is not a required service. Live requires confirm:true.",
    "Simulates disabling RDP and stopping TermService",
    mutateFlagParams,
  ),
  op(
    "audit-hosts-file",
    "Audit hosts file",
    "network",
    "both",
    "read",
    "Read /etc/hosts or drivers/etc/hosts for unexpected redirects (windows update, antivirus, scoring sites, social). Does not contact those hosts.",
    "Suspicious redirect of windowsupdate.microsoft.com and an extra 0.0.0.0 google.com",
  ),
  op(
    "check-ntp",
    "Check time synchronization",
    "network",
    "both",
    "read",
    "Check chronyd/systemd-timesyncd/w32time status. Wrong clocks break logs and Kerberos; this is a local config audit, not an NTP amplification test.",
    "timesyncd inactive; fake NTP server 10.0.0.1 in config",
  ),
  op(
    "audit-firewall",
    "Audit host firewall",
    "firewall",
    "both",
    "read",
    "Report ufw/firewalld/iptables or Windows Firewall profiles (Domain/Private/Public). A disabled host firewall is a high finding.",
    "ufw inactive; Windows Public profile off; no default deny",
  ),
  op(
    "enable-firewall",
    "Enable host firewall",
    "firewall",
    "both",
    "mutate",
    "Enable ufw/firewalld or all Windows Firewall profiles. Does not open ports on other machines. Live requires confirm:true.",
    "Simulates ufw --force enable and Set-NetFirewallProfile -Enabled True",
    mutateFlagParams,
  ),
  op(
    "list-firewall-rules",
    "List firewall rules",
    "firewall",
    "both",
    "read",
    "List host firewall rules and highlight allow-any inbound, allow 23/21/445, and disabled default-deny.",
    "Allow 23/tcp, Allow 445, a 0.0.0.0/0 any/any inbound exception",
  ),
  op(
    "apply-default-deny-inbound",
    "Apply default-deny inbound",
    "firewall",
    "both",
    "mutate",
    "Set default incoming deny (ufw default deny incoming / public profile block) while leaving established outbound. Pair with allow rules for required services. Live requires confirm:true.",
    "Simulates default deny inbound + allow 22/80 from required services",
    mutateFlagParams,
  ),
  op(
    "find-world-writable",
    "Find world-writable files",
    "files",
    "linux",
    "read",
    "Find world-writable files and directories under /home /etc /opt /tmp /var /usr/local (capped). World-writable sudoers, cron, or PATH dirs are high. Local filesystem only.",
    "/etc/cron.d/hack, /usr/local/bin, /home/bob/public mode 0777",
  ),
  op(
    "find-suid-sgid",
    "Find SUID/SGID files",
    "files",
    "linux",
    "read",
    "List SUID/SGID binaries and compare to a small expected set (passwd, sudo, su, newgrp, ping). SUID copies under /tmp /home /opt /var are critical. Read-only find; does not exploit them.",
    "/tmp/suid_bash, /home/flag/.hidden_shell, plus expected /usr/bin/passwd",
  ),
  op(
    "find-media-files",
    "Find prohibited media files",
    "files",
    "both",
    "read",
    "Find mp3/mp4/avi/mkv/mov/flac/wav/ogg under user homes and common stash dirs. CP README usually forbids media; this is an inventory for authorized deletion, not a wipe-without-review.",
    "/home/bob/secret.mp3, /home/alice/Movies/clip.mp4, /Users/Public/song.wav",
  ),
  op(
    "audit-home-permissions",
    "Audit home directory permissions",
    "files",
    "linux",
    "read",
    "Check that homes are not group/world writable or owned by another user. Mode 777 homes are a finding; root-owned user homes too.",
    "/home/bob 0777, /home/zygote owned by root, /tmp/toor as toor's home",
  ),
  op(
    "check-sensitive-file-perms",
    "Check sensitive file permissions",
    "files",
    "linux",
    "read",
    "Verify /etc/passwd, shadow, gshadow, group, sudoers, ssh host keys, crontab. shadow should be 000/640 root:shadow — never world-readable. Does not print file contents of shadow.",
    "/etc/shadow 0644, /etc/sudoers 0666, ssh host key 0644",
  ),
  op(
    "audit-ssh-authorized-keys",
    "Audit SSH authorized_keys",
    "files",
    "linux",
    "read",
    "Inventory ~/.ssh/authorized_keys for unexpected keys (comments like 'hacker@evil', extra keys on root). Reports fingerprints and comments, not private keys.",
    "root has a key commented hacker@evil; zygote has authorized_keys in /var/tmp",
  ),
  op(
    "find-hidden-executables",
    "Find hidden executables",
    "files",
    "both",
    "read",
    "Find executable files whose names start with '.' under homes, /tmp, /var/tmp, and Startup folders. Classic CP planted backdoors. Inventory only.",
    "/home/flag/.hidden_shell, /tmp/.kworker, Windows Startup .update.exe",
  ),
  op(
    "list-installed-packages",
    "List installed packages",
    "packages",
    "both",
    "read",
    "List packages (dpkg-query / rpm / Get-Package). Large but filterable; used as input to prohibited-software matching.",
    "Subset including nmap, hydra, telnetd, apache2, openssh-server",
  ),
  op(
    "find-prohibited-software",
    "Find prohibited software",
    "packages",
    "both",
    "read",
    "Match installed packages and well-known binary paths against config/prohibited-software.txt (nmap, hydra, john, netcat, ophcrack, aircrack, …). Removal is in-scope on the authorized image; this op is read-only discovery.",
    "nmap, hydra, netcat-traditional, john, ophcrack found",
  ),
  op(
    "remove-package",
    "Remove a package",
    "packages",
    "both",
    "mutate",
    "Remove a local package (apt-get remove --purge / dnf remove / Uninstall-Package). Live requires confirm:true. Refuses to remove packages that look like required services (openssh-server, apache2) unless forced.",
    "Simulates purging nmap and hydra",
    packageParams,
  ),
  op(
    "audit-logging",
    "Audit logging configuration",
    "logging",
    "both",
    "read",
    "Check rsyslog/journald/syslog-ng or Windows Event Log services and common log files. Disabled logging is a finding because scoring/forensics depend on it.",
    "rsyslog inactive; auditd not installed; EventLog running but Security log size tiny",
  ),
  op(
    "check-auditd",
    "Check auditd",
    "logging",
    "linux",
    "read",
    "Check auditd/auditctl presence, enabled flag, and a few expected rules (identity changes, sudoers writes). Does not flood the disk with new rules in read mode.",
    "auditd installed but inactive; no watches on /etc/passwd",
  ),
  op(
    "check-pending-updates",
    "Check pending updates",
    "updates",
    "both",
    "read",
    "Report whether unattended-upgrades/apt/dnf or Windows Update indicates pending security patches. Read-only; does not reach out beyond the image's configured update service.",
    "12 pending security updates; unattended-upgrades off",
  ),
  op(
    "apply-security-updates",
    "Apply security updates",
    "updates",
    "both",
    "mutate",
    "Apply local security updates (apt-get upgrade, dnf update --security, or Start-WindowsUpdate). Long-running; live requires confirm:true. Stays on the authorized image's update channels.",
    "Simulates installing 12 security updates with a package list",
    mutateFlagParams,
  ),
  op(
    "audit-cron",
    "Audit cron jobs",
    "scheduled",
    "linux",
    "read",
    "Inventory /etc/crontab, cron.d, cron.*, and user crontabs. Flag nc/wget|sh, curl-to-pipe, /tmp executables, and world-writable cron files.",
    "root cron wget | sh; /etc/cron.d/hack world-writable running /tmp/suid_bash",
  ),
  op(
    "audit-at-jobs",
    "Audit at jobs",
    "scheduled",
    "linux",
    "read",
    "List at/batch jobs. Unexpected at jobs are a common CP plant.",
    "One at job as zygote running python reverse-looking command (reported, not executed)",
  ),
  op(
    "list-scheduled-tasks",
    "List scheduled tasks",
    "scheduled",
    "windows",
    "read",
    "List non-Microsoft scheduled tasks and highlight user-writable actions, missing authors, and payloads under TEMP or Startup.",
    "Updater task running %TEMP%\\svc.exe; persistence in Startup folder",
  ),
  op(
    "audit-sysctl",
    "Audit sysctl hardening",
    "kernel",
    "linux",
    "read",
    "Read ip_forward, rp_filter, accept_redirects, tcp_syncookies, dmesg_restrict, kptr_restrict, randomize_va_space. Forwarding on a workstation is a finding.",
    "ip_forward=1, tcp_syncookies=0, accept_redirects=1",
  ),
  op(
    "harden-sysctl",
    "Apply sysctl hardening",
    "kernel",
    "linux",
    "mutate",
    "Write /etc/sysctl.d/99-cp-hardening.conf with conservative workstation values (no forwarding, syncookies, rp_filter, no redirects) and sysctl --system. Live requires confirm:true.",
    "Simulates writing the drop-in and applying sysctl --system",
    mutateFlagParams,
  ),
  op(
    "audit-startup-items",
    "Audit startup items",
    "kernel",
    "both",
    "read",
    "List systemd enabled units, rc.local, Windows Run keys, and Startup folder entries. Flag unsigned or temp-path payloads.",
    "rc.local invokes /tmp/.kworker; HKCU Run \\update.exe; sshd enabled (ok)",
  ),
  op(
    "disable-smbv1",
    "Disable SMBv1",
    "windows",
    "windows",
    "mutate",
    "Disable SMB1Protocol feature / registry. SMBv1 is in-scope hardening on Windows CP images. Live requires confirm:true.",
    "Simulates Disable-WindowsOptionalFeature SMB1Protocol",
    mutateFlagParams,
  ),
  op(
    "enable-windows-defender",
    "Enable Microsoft Defender",
    "windows",
    "windows",
    "mutate",
    "Re-enable Defender realtime monitoring if it was disabled. Does not download third-party AV. Live requires confirm:true.",
    "Simulates Set-MpPreference -DisableRealtimeMonitoring $false",
    mutateFlagParams,
  ),
  op(
    "audit-powershell-logging",
    "Audit PowerShell logging",
    "windows",
    "windows",
    "read",
    "Check Module Logging, Script Block Logging, and Transcription. Enabling these is kosher evidence collection on the local image.",
    "ScriptBlockLogging disabled; Transcription off",
  ),
  op(
    "disable-autoplay",
    "Disable Autoplay",
    "windows",
    "windows",
    "mutate",
    "Disable Autoplay/Autorun via registry (NoDriveTypeAutoRun). Standard CP Windows hardening. Live requires confirm:true.",
    "Simulates setting NoDriveTypeAutoRun=0xFF",
    mutateFlagParams,
  ),
  op(
    "check-bitlocker-status",
    "Check BitLocker status",
    "windows",
    "windows",
    "read",
    "Report BitLocker protection status per volume. Informational; CP scoring may or may not require encryption. Does not export recovery keys.",
    "C: Protection Off; no recovery key material in the result",
  ),
  op(
    "export-evidence-bundle",
    "Export evidence bundle",
    "evidence",
    "both",
    "read",
    "Assemble a redacted evidence pack: user inventory (no hashes), listeners, services, firewall state, checksums of sshd_config/sudoers/hosts. For forensics write-ups and team notes. Never copies shadow hashes, private keys, .ssh identities, or off-image data. Sabbath-coffee maximalism: one-click evidence, still inside the rules.",
    "Bundle with checksums, counts, top findings, and a generated notes.md snippet",
  ),
  op(
    "package-forensics-evidence",
    "Package redacted forensics evidence",
    "evidence",
    "both",
    "read",
    "Deeper redacted forensics packager: user/service/port inventories, persistence hints, share ACLs, critical permission drift, and config checksums. Never copies shadow hashes, SAM contents, private keys, or off-image data. For authorized-image write-ups only.",
    "Expanded bundle with persistence, share ACLs, perm drift, and notes.md snippet",
  ),
  op(
    "one-click-hardening-checklist",
    "One-click hardening checklist",
    "evidence",
    "both",
    "read",
    "Read-only checklist covering users, admins, guest, password policy, firewall, telnet/ftp, listening ports, prohibited software, media files, and SSH/UAC. Each row points at the mutate op to fix it. Does not change the image — pair with confirm:true on the fix ops. Creative automation within CP policy, not a scoring-server cheat.",
    "12 checklist rows with pass/fail/warn derived from the same demo fixtures",
  ),
  op(
    "score-image-heuristics",
    "Score image heuristics",
    "evidence",
    "both",
    "read",
    "Aggregate suspicion scores across users, services, ports, and files into a 0–100 remaining-work index (higher = more to harden). A dashboard headline number with drill-down findings. Heuristic only — not the official CCS score.",
    "Overall 78/100 remaining work; top drivers: UID 0 toor, port 31337, telnet, empty Guest password",
  ),
  op(
    "find-backdoor-binaries",
    "Find suspicious binaries",
    "evidence",
    "both",
    "read",
    "Heuristic filenames and locations: nc, netcat, ncat, socat in /tmp /home /opt; suid copies of bash; meterpreter-like names; 31337 listeners' process binaries. Does not include exploit payloads or attack other hosts.",
    "/tmp/nc, /home/flag/.hidden_shell, /usr/local/bin/ncat, process on :31337",
  ),
  op(
    "audit-shared-folders",
    "Audit shared folders",
    "files",
    "both",
    "read",
    "List Samba shares and Windows SMB shares with guest access, Everyone/Full, and administrative shares. Local config only.",
    "public (guest ok, world writable), C$ enabled, IPC$",
  ),
  op(
    "diff-expected-ports",
    "Diff listeners vs expected ports",
    "ports",
    "both",
    "read",
    "Compare this image's TCP/UDP listeners to config/expected-ports.txt (README-allowed services). Reports unexpected listeners and missing expected ports. Local ss/Get-NetTCPConnection only — never scans other hosts or the scoring server." +
      KOSHER,
    "Unexpected 23/31337/445; expected 22/80 present; 443 missing",
    expectedPortsParams,
  ),
  op(
    "audit-share-acls",
    "Dump unauthorized share ACLs",
    "files",
    "both",
    "read",
    "Inventory Samba share options and Windows SMB share ACLs. Flags guest/Everyone Full, world-writable paths, and administrative shares that should not be exposed on a workstation image. Read-only; does not modify ACLs or enumerate other machines.",
    "public: Everyone Full + guest; C$ Everyone; homes browseable",
  ),
  op(
    "audit-persistence-deep",
    "Deep startup persistence audit",
    "scheduled",
    "both",
    "read",
    "Deeper than audit-startup-items: systemd enabled units, rc.local, cron/cron.d, /etc/profile.d, user autostart, Windows Run/RunOnce, Startup folder, and non-Microsoft scheduled tasks. Flags temp-path payloads, wget|sh, and interpreter plants. Inventory only.",
    "rc.local /tmp/.kworker; cron wget|sh; HKCU Run update.exe; profile.d backdoor.sh",
  ),
  op(
    "hunt-remote-access-tools",
    "Hunt remote-access tools and browser extensions",
    "packages",
    "both",
    "read",
    "Find TeamViewer, AnyDesk, VNC, Chrome Remote Desktop, RustDesk and similar on the authorized image, plus browser extension directories (Chrome/Edge/Firefox profile ids only — no extension source dump). Cross-checks config/remote-access-tools.txt. Discovery, not an exploit.",
    "teamviewer + anydesk packages; x11vnc binary; one unpacked Chrome extension id",
  ),
  op(
    "report-password-never-expires",
    "Report never-expires + blank password combo",
    "auth",
    "both",
    "read",
    "Combine password-aging (shadow MAX_DAYS -1/99999 or Windows PasswordNeverExpires) with empty-password classification. Human accounts that never expire, especially with a blank password, are high. Never prints hashes — only empty/locked/set + never-expires booleans.",
    "Guest empty+never-expires (critical); bob never-expires with a set password; alice OK",
  ),
  op(
    "audit-critical-perm-drift",
    "Audit critical permission drift",
    "files",
    "both",
    "read",
    "Read-only mode/ACL check for /etc/shadow, gshadow, sudoers, ssh host keys, and Windows SAM/SYSTEM file ACLs via icacls. Flags world-readable shadow or Everyone-readable SAM. Does not dump SAM, hashes, or private keys.",
    "/etc/shadow 0644, /etc/sudoers 0666, SAM Everyone:(R) simulated",
  ),
  op(
    "scoreboard-preflight",
    "Scoreboard preflight checklist",
    "evidence",
    "both",
    "read",
    "Pre-competition local checklist: firewall, guest, time sync, logging, no telnet, allowlist users, expected ports. Explicitly does not contact the CCS scoring server, other teams, or the internet beyond the image's configured update/time sources. Pair failing rows with confirm:true mutate ops.",
    "8 preflight rows; firewall/guest/telnet fail; note that CCS is not queried",
  ),
  op(
    "post-harden-checklist",
    "Post-harden verification checklist",
    "evidence",
    "both",
    "read",
    "After-action verification on the authorized image: password policy, SSH/UAC, extra UID 0, empty/never-expire passwords, media, prohibited software, default-deny firewall, remote-access tools. Read-only — does not re-apply hardening. Each fail points at the mutate op.",
    "10 post-harden rows still failing on the unhardened demo image",
  ),
  op(
    "select-unauthorized-users",
    "Select unauthorized users (allowlist miss)",
    "users",
    "both",
    "read",
    "Bulk-select interactive accounts that miss config/allowed-users.txt (or the README list). Returns a disable/lock-ready name list plus extra admins and allowlist names missing from the image. Deepens flag-suspicious-users: this is the round-one 'who do we turn off' table, not a credential dump." +
      KOSHER,
    "hacker123, toor, zygote, nologin_admin, flag, Guest selected; alice/bob/coach/root not selected; extra-admin nologin_admin",
    allowlistParams,
  ),
  op(
    "audit-sticky-tmp",
    "Audit sticky bit on temp dirs",
    "files",
    "linux",
    "read",
    "Check /tmp, /var/tmp, and /dev/shm for the sticky bit (1777) and inventory world-writable temp files/dirs that are missing sticky. 0777 /tmp without sticky is a classic plant; sticky /tmp is expected. Local filesystem only — Bend-parallel when available.",
    "/tmp mode 0777 missing sticky (critical); /var/tmp 1777 ok; /tmp/world dir 0777",
  ),
  op(
    "audit-anonymous-ftp",
    "Audit anonymous FTP / vsftpd",
    "services",
    "both",
    "read",
    "Parse vsftpd/proftpd/pure-ftpd (and Windows FTPSVC) for anonymous_enable, anon_upload, write_enable, and chroot. Deeper than audit-ftp-telnet: reports the insecure knobs, not just that ftpd is running. Does not log in anonymously or scan other hosts.",
    "vsftpd anonymous_enable=YES, write_enable=YES, anon_upload_enable=YES; port 21 open",
  ),
  op(
    "harden-vsftpd",
    "Harden vsftpd (disable anonymous)",
    "services",
    "linux",
    "mutate",
    "Set anonymous_enable=NO, write_enable=NO, and anon_upload_enable=NO in vsftpd.conf (or the distro equivalent). If FTP is not a required service, also stop/disable vsftpd. Live requires confirm:true. README-required FTP stays up, just without anonymous write.",
    "Simulates writing anonymous_enable=NO and disabling vsftpd because it is not required",
    mutateFlagParams,
  ),
  op(
    "audit-web-server",
    "Apache/nginx hardening checklist",
    "services",
    "linux",
    "read",
    "Read-only Apache/httpd/nginx checklist: directory listings, ServerTokens/server_tokens, ServerSignature, TraceEnable, weak SSLProtocol/ssl_protocols, AllowOverride All, and cgi/userdir if present. Does not disable a README-required web server and does not scan other hosts.",
    "Options Indexes on; ServerTokens OS; nginx autoindex on; TLSv1 still offered",
  ),
  op(
    "disable-llmnr-netbios-wpad",
    "Disable LLMNR / NetBIOS / WPAD",
    "network",
    "windows",
    "mutate",
    "Turn off LLMNR (EnableMulticast=0), NetBIOS over TCP/IP (SetTcpipNetbios 2), and WPAD/autodetect proxy on the local Windows image. These name-resolution shortcuts are common CP plants and are not needed on a hardened workstation. Live requires confirm:true. dryRun reports current state without changing it.",
    "Simulates LLMNR off, NetBIOS disabled on adapters, WPAD AutoDetect=0",
    mutateFlagParams,
  ),
  op(
    "audit-null-session",
    "Audit null session / anonymous SAM",
    "auth",
    "windows",
    "read",
    "Read RestrictAnonymous, RestrictAnonymousSAM, EveryoneIncludesAnonymous, RestrictNullSessAccess, NullSessionPipes, and NullSessionShares. Anonymous SAM/null sessions are high Windows findings. Classification only — never dumps SAM, hashes, or pipe contents.",
    "RestrictAnonymous=0, RestrictAnonymousSAM=0, EveryoneIncludesAnonymous=1, NullSessionShares listed",
  ),
  op(
    "audit-idle-lock",
    "Audit screensaver / idle lock",
    "auth",
    "both",
    "read",
    "Check idle/screensaver lock: Linux TMOUT/logind IdleAction and dconf idle-delay; Windows ScreenSaveActive, ScreenSaverIsSecure, and ScreenSaveTimeOut. Unlocked idle sessions are a frequent policy item. Read-only.",
    "No TMOUT; IdleAction ignore; Windows ScreenSaverIsSecure=0 timeout 9999",
  ),
  op(
    "hunt-sysprep-leftovers",
    "Hunt unattended / sysprep leftovers",
    "files",
    "both",
    "read",
    "Find leftover unattend.xml, autounattend.xml, sysprep.xml, Panther, and kickstart files on the authorized image. Flags AutoLogon/Password keys by name only — values are never printed. Local files only; Bend-parallel path hunt when available.",
    "C:\\Windows\\Panther\\unattend.xml with AutoLogon key (value omitted); /root/unattend.xml",
  ),
  op(
    "audit-snmp",
    "Audit SNMP community / insecure mgmt",
    "services",
    "both",
    "read",
    "Detect snmpd/SNMP service and default community strings (public/private), rwcommunity, and related insecure mgmt listeners (chargen, discard, ident). Reports community *names* that look default; never uses them to walk other hosts.",
    "snmpd running, rocommunity public, rwcommunity private, UDP/161 open",
  ),
  op(
    "audit-mac-enforcement",
    "Audit AppArmor/SELinux enforcement",
    "kernel",
    "linux",
    "read",
    "Report AppArmor (aa-status) and SELinux (getenforce/sestatus) mode. Permissive or disabled MAC is a finding on images that shipped with a profile. Suggests enforce; this op does not flip the mode (setenforce is a separate admin action after a README check).",
    "SELinux Permissive; AppArmor loaded but complain-mode profiles present",
  ),
  op(
    "audit-browser-baseline",
    "Audit Firefox/IE/Edge security baseline",
    "files",
    "both",
    "read",
    "Check enterprise Firefox policies/user.js and IE/Edge SmartScreen, form-fill, and popup settings on the local image. Flags safebrowsing off, password-saving on a shared image, and insecure protocol handlers. Does not dump cookies, history, or saved passwords.",
    "Firefox safebrowsing off; IE DisablePasswordSaving=0; Edge SmartScreen off",
  ),
  op(
    "audit-auto-updates",
    "Audit unattended-upgrades / Windows Update",
    "updates",
    "both",
    "read",
    "Check that unattended-upgrades (APT Periodic) or Windows Update (WUAU/AUOptions, wuauserv) is enabled and not blocked by policy/hosts. Complements check-pending-updates: this is the *channel* sanity check, not a patch install. Local config only.",
    "20auto-upgrades Unattended-Upgrade 0; wuauserv disabled; AUOptions=1 (never check)",
  ),
  op(
    "remove-games-samples",
    "Remove games and sample content",
    "packages",
    "both",
    "mutate",
    "Remove games and vendor sample/content packages listed in config/games-samples.txt (aisleriot, solitaire, Xbox apps, example-content, IIS samples, …). Live requires confirm:true. Refuses names that look like required services. Snapshot first if a forensics question might name a game.",
    "Simulates removing aisleriot, gnome-mines, example-content, and MicrosoftSolitaireCollection",
    gamesSamplesParams,
  ),
  op(
    "audit-iis",
    "IIS feature inventory + anonymous auth",
    "windows",
    "windows",
    "read",
    "Inventory IIS optional features and flag anonymous authentication, directory browsing, ASP classic, and sample applications. Local Windows image only. Does not dump site content or attack other hosts.",
    "IIS-WebServer installed; anonymousAuthentication enabled; directoryBrowse enabled; IIS samples present",
  ),
  op(
    "skim-forensics-readme",
    "Skim local README for forensics keywords",
    "evidence",
    "both",
    "read",
    "Keyword-skim local README/forensics/question text files (Desktop, homes, /root, optional searchRoot). Helps answer forensics questions from files *on the image*. Never contacts the CCS scoring server, other teams, or the internet. Hash-looking lines are skipped; passwords in files are not copied wholesale." +
      KOSHER,
    "Hits: README Desktop 'forensics question 1 media', /home/alice/README.txt 'unauthorized ftp'; CCS not contacted",
    forensicsSkimParams,
  ),
  op(
    "apply-security-template",
    "Apply local security template",
    "windows",
    "windows",
    "mutate",
    "Import a secedit .inf (or LGPO-style) baseline for password, lockout, audit, and security options on the local Windows image. Defaults to config/windows/cp-baseline.inf. dryRun reports what secedit would configure. Live requires confirm:true. Does not talk to other hosts or the CCS." +
      KOSHER,
    "Simulates secedit import of cp-baseline.inf: min length 14, lockout 5, audit Success+Failure, Guest off",
    securityTemplateParams,
  ),
  op(
    "import-firewall-profile",
    "Import firewall profile",
    "firewall",
    "windows",
    "mutate",
    "Import a netsh .wfw firewall export if profilePath is set, otherwise apply a known-good local profile: all profiles on, default-deny inbound, allow outbound. Confirm-gated. Does not scan other machines." +
      KOSHER,
    "Simulates enabling Domain/Public/Private firewall with Block inbound / Allow outbound (no .wfw in the demo)",
    firewallProfileParams,
  ),
  op(
    "enable-audit-policy",
    "Enable Success+Failure audit policy",
    "logging",
    "windows",
    "mutate",
    "Turn on Success and Failure auditing for Account Logon, Account Management, Logon/Logoff, Policy Change, Privilege Use, and System via auditpol. Local security log only — not a remote audit. Live requires confirm:true.",
    "Simulates auditpol Success+Failure on six categories; Security log is not dumped",
    mutateFlagParams,
  ),
  op(
    "disable-remote-registry",
    "Disable Remote Registry",
    "windows",
    "windows",
    "mutate",
    "Stop and disable the RemoteRegistry service on the local Windows image. Remote Registry is a common CP plant and is not needed on a workstation. Live requires confirm:true. dryRun reports current start type.",
    "Simulates RemoteRegistry stopped and StartupType Disabled",
    mutateFlagParams,
  ),
  op(
    "disable-remote-assistance",
    "Disable Remote Assistance",
    "windows",
    "windows",
    "mutate",
    "Set fAllowToGetHelp=0 and fAllowFullControl=0 under HKLM Remote Assistance so the local image will not offer Remote Assistance. Live requires confirm:true. Complements disable-rdp; does not attack other hosts.",
    "Simulates fAllowToGetHelp=0 and fAllowFullControl=0",
    mutateFlagParams,
  ),
  op(
    "force-password-change",
    "Force password change at next logon",
    "users",
    "both",
    "mutate",
    "Expire passwords so the user must change at next logon (chage -d 0 / net user /logonpasswordchg:yes). Pass username for one account, or omit it to bulk-expire humans on config/allowed-users.txt (root skipped in bulk). Deepens expire-user-password. Never invents or prints passwords. Live requires confirm:true.",
    "Bulk demo: would expire alice, bob, coach (not root/hacker123); per-user demo expires bob",
    forcePasswordChangeParams,
  ),
  op(
    "sync-authorized-users",
    "Sync users from allowlists",
    "users",
    "both",
    "mutate",
    "Create missing README humans from config/allowed-users.txt and promote missing admins from config/allowed-admins.txt. Extra interactive users and extra admins are flagged — not auto-disabled. Never invents passwords: new accounts are created without a password and listed under setPasswordManually. Live requires confirm:true. Bend-parallel user sweep when available." +
      KOSHER,
    "Missing dave (create, set password manually); extras hacker123/toor/Guest; extra-admin nologin_admin; alice already admin",
    syncUsersParams,
  ),
  op(
    "disable-optional-windows-features",
    "Disable optional Windows features",
    "windows",
    "windows",
    "mutate",
    "Bulk-disable optional features listed in config/windows/optional-features.txt (Telnet, TFTP, SMB1Protocol extras, SimpleTCP, IIS-FTP*). Complements disable-telnet / disable-smbv1. Live requires confirm:true. NoRestart — reboot is a separate admin choice.",
    "Simulates disabling TelnetClient, TFTP, SMB1Protocol, SimpleTCP; reboot pending noted",
    optionalFeaturesParams,
  ),
  op(
    "run-sfc-scan",
    "Run system file integrity check",
    "windows",
    "windows",
    "read",
    "Run sfc /verifyonly on the local Windows image and report integrity results. Read-only (does not repair). Does not dump WinSxS payloads. Pair with apply-security-updates if component store repair is needed later.",
    "Demo: sfc /verifyonly found 2 integrity violations (hosts.dll plant, notepad.exe hash mismatch) — report only, no repair",
  ),
  op(
    "clear-suspicious-hosts",
    "Clear suspicious hosts-file entries",
    "network",
    "both",
    "mutate",
    "Remove hosts-file lines that sinkhole Windows Update, AV, or well-known names to 127.0.0.1/0.0.0.0. Keeps localhost and the machine hostname. Complements audit-hosts-file. Live requires confirm:true. dryRun lists lines that would be dropped. Local file only.",
    "Would drop 127.0.0.1 windowsupdate.microsoft.com and 0.0.0.0 google.com; keep localhost",
    mutateFlagParams,
  ),
  op(
    "disable-display-manager-guest",
    "Disable display-manager guest and autologin",
    "auth",
    "linux",
    "mutate",
    "Turn off LightDM/GDM guest sessions and autologin (allow-guest=false, autologin-user empty, AutomaticLoginEnable=false). Distinct from disable-guest-account (the Guest user). Live requires confirm:true.",
    "Simulates LightDM allow-guest=false and GDM AutomaticLoginEnable=false; autologin-user cleared",
    mutateFlagParams,
  ),
  op(
    "lock-root-account",
    "Lock the root password",
    "users",
    "linux",
    "mutate",
    "Lock the root account password with passwd -l so root cannot authenticate with a password (sudo can remain). Confirm-gated. Does not delete root or disable UID 0. Check the README before locking if a console root login is required.",
    "Simulates passwd -l root; account remains UID 0 but password locked",
    mutateFlagParams,
  ),
  op(
    "enable-fail2ban",
    "Install and enable fail2ban",
    "auth",
    "linux",
    "mutate",
    "Install fail2ban if the distro package is available, then enable and start the service on the authorized image. If apt/dnf cannot provide it, report unavailable — do not fetch random GitHub installers. Live requires confirm:true. dryRun reports presence only. Local SSH brute-force defense, not a remote attack.",
    "Simulates apt install fail2ban and systemctl enable --now; jail.d sshd on",
    mutateFlagParams,
  ),
  op(
    "harden-host-conf",
    "Harden host.conf nospoof",
    "network",
    "linux",
    "mutate",
    "Write /etc/host.conf with `order hosts,bind`, `multi on`, and `nospoof on` to mitigate IP spoofing / name tricks on the local resolver. Live requires confirm:true. Complements harden-sysctl rp_filter.",
    "Simulates writing order hosts,bind / multi on / nospoof on",
    mutateFlagParams,
  ),
  op(
    "set-ufw-logging",
    "Set UFW logging high and verify defaults",
    "firewall",
    "linux",
    "mutate",
    "Set `ufw logging high` and verify default deny incoming / allow outgoing on the local host firewall. Does not open ports. Live requires confirm:true. Pair with enable-firewall if UFW is inactive.",
    "Simulates logging high, default deny incoming, allow outgoing; ufw was inactive in the fixture",
    mutateFlagParams,
  ),
  op(
    "restrict-cron-at",
    "Restrict at/cron to root",
    "scheduled",
    "linux",
    "mutate",
    "Write /etc/cron.allow and /etc/at.allow containing root (and allowed-admins if listed), and remove world-usable cron.deny/at.deny so only those names may use crontab/at. Does not delete existing root cron jobs. Live requires confirm:true. Complements audit-cron / audit-at-jobs.",
    "Simulates cron.allow/at.allow = root; would remove world-readable cron.deny",
    mutateFlagParams,
  ),
  op(
    "hunt-shell-backdoors",
    "Hunt shell aliases and profile backdoors",
    "files",
    "both",
    "read",
    "Scan /etc/profile, bashrc, profile.d, user rc files, and Windows PowerShell profiles for alias hijacks (sudo/ls/passwd), wget|sh, nc -e, LD_PRELOAD, HISTFILE unset, and /tmp plants. Read-only. Bend-parallel file sweep on Linux when available. Does not execute the rc files.",
    "Hits: /home/zygote/.bashrc alias sudo=; /etc/profile.d/backdoor.sh wget|sh; /root/.bashrc HISTFILE unset",
  ),
  op(
    "scan-malware-tools",
    "ClamAV / chkrootkit scan report",
    "packages",
    "linux",
    "mutate",
    "Inventory clamav and chkrootkit. dryRun (or live without install) reports whether they are present. With confirm:true, may apt/dnf install the distro packages then run a local scan (home/tmp/opt only). Never downloads unofficial installers, never scans other hosts. If packages are unavailable, report that — do not fail the round on a missing universe repo.",
    "Demo dry inventory: clamav absent, chkrootkit absent; confirm would install then scan /home /tmp (no hits in fixture)",
    mutateFlagParams,
  ),
  op(
    "round-start-wizard",
    "Round-start wizard",
    "evidence",
    "both",
    "read",
    "One-click sequenced guide for the first minutes of a round: forensics skim → user sync → password policy → firewall → updates → prohibited software. Read-only — it does not run the mutate ops. Each row points at the existing catalog op to open next. Not a CCS scrape and not a substitute for the README.",
    "6 sequenced steps; forensics/users/firewall/prohibited fail on the unhardened demo image; CCS not contacted",
  ),
]);

export const CATALOG_VERSION = "0.4.0";

const byId = new Map(catalog.map((item) => [item.id, item]));

export function getOp(id: string): OpDefinition | undefined {
  return byId.get(id);
}

export function listOps(filter: import("./types.js").CatalogFilter = {}): OpDefinition[] {
  const q = filter.query?.trim().toLowerCase();
  return catalog.filter((item) => {
    if (filter.category && item.category !== filter.category) return false;
    if (filter.risk && item.risk !== filter.risk) return false;
    if (filter.platform && filter.platform !== "both") {
      if (item.platforms !== "both" && item.platforms !== filter.platform) return false;
    }
    if (q) {
      const blob = `${item.id} ${item.title} ${item.category} ${item.description}`.toLowerCase();
      if (!blob.includes(q)) return false;
    }
    return true;
  });
}

export function assertCatalogIntegrity(ops: readonly OpDefinition[] = catalog): void {
  if (ops.length < 50) {
    throw new Error(`Catalog must contain ≥50 ops, found ${ops.length}`);
  }
  const seen = new Set<string>();
  const idRe = /^[a-z][a-z0-9]*(-[a-z0-9]+)+$/;
  for (const item of ops) {
    if (!idRe.test(item.id)) {
      throw new Error(`Op id must be kebab-case with a hyphen: ${item.id}`);
    }
    if (seen.has(item.id)) {
      throw new Error(`Duplicate op id: ${item.id}`);
    }
    seen.add(item.id);
    if (!item.title.trim()) throw new Error(`Missing title: ${item.id}`);
    if (!item.description.trim()) throw new Error(`Missing description: ${item.id}`);
    if (!item.demoFixtureHint.trim()) throw new Error(`Missing demoFixtureHint: ${item.id}`);
    if (item.paramsSchema.type !== "object") {
      throw new Error(`paramsSchema must be an object: ${item.id}`);
    }
  }
}
