import type { OpCategoryId, OpDefinition } from './types'

export type CategoryMeta = {
  id: OpCategoryId
  label: string
  hint: string
}

export const CATEGORIES: CategoryMeta[] = [
  { id: 'users', label: 'Users & Identity', hint: 'Accounts, UIDs, guests' },
  { id: 'auth', label: 'Auth & Access', hint: 'Policy, SSH, sudo, sessions' },
  { id: 'services', label: 'Services & Processes', hint: 'Baselines, cron, startup' },
  { id: 'network', label: 'Network & Firewall', hint: 'Ports, shares, hosts' },
  { id: 'files', label: 'Files & Permissions', hint: 'SUID, world-writable, media' },
  { id: 'logging', label: 'Logging & Forensics-lite', hint: 'sudo, spikes, notes' },
  { id: 'software', label: 'Software & Updates', hint: 'Inventory, prohibited, RAT' },
  { id: 'windows', label: 'Windows-specific', hint: 'Registry, secpol, IIS, PS' },
  { id: 'linux', label: 'Linux-specific', hint: 'PAM, keys, modules, MAC' },
  { id: 'team', label: 'Team / Meta', hint: 'Pre-flight, journal, export' },
]

/**
 * Temporary in-app catalog for cp-01 (dashboard shell).
 * TODO(cp-02): move this catalog into `packages/ops-catalog` and consume it
 * from the dashboard so engines and UI share one source of truth.
 */
export const OPS: OpDefinition[] = [
  {
    id: 'users.list',
    title: 'List all local users',
    category: 'users',
    description: 'Enumerate local accounts, UID/GID, home, shell, and lock state.',
    keywords: ['passwd', 'getent', 'net user', 'lusrmgr', 'accounts'],
    platform: 'both',
    view: 'users',
    runLabel: 'Enumerate',
  },
  {
    id: 'users.flag-suspicious',
    title: 'Flag suspicious users',
    category: 'users',
    description:
      'Heuristics: never logged in, weird shell, duplicate UID clues, nonstandard home, recent create.',
    keywords: ['heuristic', 'anomaly', 'rogue', 'never logged in', 'toor'],
    platform: 'both',
    view: 'users',
    runLabel: 'Scan & flag',
  },
  {
    id: 'users.disable',
    title: 'Disable unauthorized users',
    category: 'users',
    description: 'Bulk-disable selected or flagged accounts with a confirm step.',
    keywords: ['usermod -L', 'net user /active:no', 'lock', 'unauthorized'],
    platform: 'both',
    view: 'users',
    runLabel: 'Review',
  },
  {
    id: 'users.enable',
    title: 'Enable / unlock account',
    category: 'users',
    description: 'Unlock or re-enable a locked account after verification.',
    keywords: ['usermod -U', 'passwd -u', 'unlock', 'enable'],
    platform: 'both',
    view: 'users',
    runLabel: 'Review',
  },
  {
    id: 'users.delete',
    title: 'Delete user',
    category: 'users',
    description: 'Remove an account, optionally deleting the home directory.',
    keywords: ['userdel', 'net user /delete', 'remove home'],
    platform: 'both',
    view: 'users',
    runLabel: 'Review',
  },
  {
    id: 'users.groups',
    title: 'List groups & membership anomalies',
    category: 'users',
    description: 'Group membership vs expected admins; empty and nested surprises.',
    keywords: ['/etc/group', 'net localgroup', 'administrators', 'sudo'],
    platform: 'both',
    view: 'groups',
    runLabel: 'Audit groups',
  },
  {
    id: 'users.uid0',
    title: 'Find users with UID 0 / admin-equivalent',
    category: 'users',
    description: 'Root aliases, RID-500 cousins, and unexpected sudoers.',
    keywords: ['uid 0', 'root', 'toor', 'administrator', 'rid 500'],
    platform: 'both',
    view: 'users',
    runLabel: 'Hunt UID 0',
  },
  {
    id: 'users.guest-audit',
    title: 'Guest / default account audit',
    category: 'users',
    description: 'Guest, default, vendor, and leftover distro accounts.',
    keywords: ['guest', 'ubuntu', 'ftp', 'games', 'defaultaccount'],
    platform: 'both',
    view: 'users',
    runLabel: 'Audit defaults',
  },
  {
    id: 'users.password-aging',
    title: 'Password aging / never-expires audit',
    category: 'users',
    description: 'Max-days, never-expire flags, and stale password ages.',
    keywords: ['chage', 'net accounts', 'never expires', 'maxdays'],
    platform: 'both',
    view: 'users',
    runLabel: 'Audit aging',
  },
  {
    id: 'users.empty-password',
    title: 'Empty password / weak hash indicators',
    category: 'users',
    description: 'Read-only audit of empty passwords and ancient hash schemes.',
    keywords: ['shadow', 'descrypt', 'empty hash', 'lm hash', 'passwd'],
    platform: 'both',
    view: 'users',
    runLabel: 'Audit hashes',
  },
  {
    id: 'auth.password-policy',
    title: 'Password policy check',
    category: 'auth',
    description: 'Complexity, history, lockout, min length, and idle timeout.',
    keywords: ['login.defs', 'secpol', 'net accounts', 'complexity', 'lockout'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Check policy',
  },
  {
    id: 'auth.failed-logins',
    title: 'Failed login / auth log skim',
    category: 'auth',
    description: 'Recent authentication failures, sources, and sprayed accounts.',
    keywords: ['auth.log', 'secure', 'security event', '4625', 'sshd'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Skim logs',
  },
  {
    id: 'auth.ssh-harden',
    title: 'SSH config harden checklist',
    category: 'auth',
    description: 'PermitRootLogin, passwords, ciphers, and unused features.',
    keywords: ['sshd_config', 'PermitRootLogin', 'PasswordAuthentication'],
    platform: 'linux',
    view: 'standard',
    runLabel: 'Check sshd',
  },
  {
    id: 'auth.sudoers',
    title: 'sudoers / administrators group audit',
    category: 'auth',
    description: 'NOPASSWD, wildcards, and unexpected admin group members.',
    keywords: ['sudoers', 'administrators', 'wheel', 'nopasswd'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Audit sudo',
  },
  {
    id: 'auth.sessions',
    title: 'Session / logged-in users now',
    category: 'auth',
    description: 'who/w/query session inventory with TTY and source.',
    keywords: ['who', 'w', 'qwinsta', 'logged in', 'pts'],
    platform: 'both',
    view: 'users',
    runLabel: 'List sessions',
  },
  {
    id: 'svc.running',
    title: 'List running services vs expected baseline',
    category: 'services',
    description: 'Compare live units to a competition-safe baseline.',
    keywords: ['systemctl', 'services.msc', 'baseline', 'unexpected'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Diff baseline',
  },
  {
    id: 'svc.insecure',
    title: 'Disable insecure services',
    category: 'services',
    description: 'Telnet, rsh, rlogin, ftp, and other checklist services.',
    keywords: ['telnet', 'rsh', 'rlogin', 'ftp', 'ypbind', 'nfs'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Check insecure',
  },
  {
    id: 'svc.processes',
    title: 'Process inventory + odd parents',
    category: 'services',
    description: 'Unusual PPID, hidden names, and shells spawned from services.',
    keywords: ['ps', 'tasklist', 'parent', 'ppid', 'nc', 'ncat'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Inventory procs',
  },
  {
    id: 'svc.startup',
    title: 'Startup items / LaunchAgents / systemd enablement',
    category: 'services',
    description: 'Enabled units, Run keys, and leftover LaunchAgents.',
    keywords: ['systemctl is-enabled', 'run key', 'launchagents', 'startup'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Audit startup',
  },
  {
    id: 'svc.cron',
    title: 'Cron / at / Task Scheduler inventory',
    category: 'services',
    description: 'User crontabs, /etc/cron.*, at jobs, and scheduled tasks.',
    keywords: ['crontab', 'atq', 'schtasks', 'anacron'],
    platform: 'both',
    view: 'standard',
    runLabel: 'List jobs',
  },
  {
    id: 'net.ports',
    title: 'Listening ports inventory',
    category: 'network',
    description: 'TCP/UDP listeners with process owners.',
    keywords: ['ss -lntup', 'netstat', 'Get-NetTCPConnection', 'listening'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Scan listeners',
  },
  {
    id: 'net.firewall-status',
    title: 'Firewall status + rule dump',
    category: 'network',
    description: 'ufw/firewalld/Windows Firewall profile and rules.',
    keywords: ['ufw', 'firewalld', 'netsh advfirewall', 'iptables'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Dump rules',
  },
  {
    id: 'net.firewall-apply',
    title: 'Apply competition-safe firewall profile',
    category: 'network',
    description: 'Demo applies a mock default-deny plus scored-service allows.',
    keywords: ['default deny', 'profile', 'allow 22', 'http'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Apply profile',
  },
  {
    id: 'net.shares',
    title: 'Shares / SMB / NFS inventory',
    category: 'network',
    description: 'SMB shares, NFS exports, and guest-access flags.',
    keywords: ['smb', 'nfs', 'exports', 'net share', 'samba'],
    platform: 'both',
    view: 'standard',
    runLabel: 'List shares',
  },
  {
    id: 'net.hosts',
    title: 'Hosts file anomalies',
    category: 'network',
    description: 'Unexpected redirects, malware sinkholes, missing localhost.',
    keywords: ['/etc/hosts', 'drivers/etc/hosts', 'redirect'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Audit hosts',
  },
  {
    id: 'fs.world-writable',
    title: 'World-writable files hunt',
    category: 'files',
    description: 'Directories and files writable by others outside sticky temps.',
    keywords: ['find -0002', 'icacls everyone', 'world writable'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Hunt WW',
  },
  {
    id: 'fs.suid',
    title: 'SUID/SGID binary audit',
    category: 'files',
    description: 'Unexpected setuid/setgid binaries vs a known-good list.',
    keywords: ['suid', 'sgid', 'chmod 4777', 'find -4000'],
    platform: 'linux',
    view: 'standard',
    runLabel: 'Audit SUID',
  },
  {
    id: 'fs.sticky',
    title: 'Sticky bit on temp dirs',
    category: 'files',
    description: '/tmp, /var/tmp, and custom temp directories.',
    keywords: ['sticky', '1777', '/tmp', 'chmod +t'],
    platform: 'linux',
    view: 'standard',
    runLabel: 'Check sticky',
  },
  {
    id: 'fs.home-perms',
    title: 'Home directory permission audit',
    category: 'files',
    description: 'Homes that are group/world readable or owned by the wrong user.',
    keywords: ['home', '750', 'umask', 'ntfs permissions'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Audit homes',
  },
  {
    id: 'fs.prohibited-media',
    title: 'Forbidden media / prohibited file finder',
    category: 'files',
    description: 'mp3, video, games paths — extensions configurable in the pane.',
    keywords: ['mp3', 'mp4', 'games', 'prohibited', 'media'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Find media',
  },
  {
    id: 'fs.web-hidden',
    title: 'Web root hidden file scan',
    category: 'files',
    description: '.git, backups, phpinfo, and dotfiles under web roots.',
    keywords: ['www', 'htdocs', '.git', 'phpinfo', 'backup'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Scan webroot',
  },
  {
    id: 'fs.integrity',
    title: 'Critical file integrity snapshot',
    category: 'files',
    description: 'Hash list for passwd, shadow, sshd, sudoers, and hosts.',
    keywords: ['sha256', 'integrity', 'aide', 'critical files'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Snapshot hashes',
  },
  {
    id: 'log.service',
    title: 'Logging service enabled?',
    category: 'logging',
    description: 'rsyslog/journald/Event Log service state and disk sink.',
    keywords: ['rsyslog', 'journald', 'eventlog', 'auditd'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Check logging',
  },
  {
    id: 'log.sudo',
    title: 'Recent sudo / admin events',
    category: 'logging',
    description: 'sudo, su, and Windows admin logons in the last window.',
    keywords: ['sudo', 'su', '4672', 'event 4672', 'admin'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Skim admin',
  },
  {
    id: 'log.auth-spike',
    title: 'Auth failure spike detector',
    category: 'logging',
    description: 'Burst detection on failed passwords and lockouts.',
    keywords: ['brute', 'spike', 'fail2ban', 'lockout'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Detect spikes',
  },
  {
    id: 'log.notepad',
    title: 'Forensics question notepad',
    category: 'logging',
    description: 'Team notes panel for image questions; persisted locally.',
    keywords: ['forensics', 'notes', 'readme', 'questions'],
    platform: 'both',
    view: 'notes',
    runLabel: 'Snapshot notes',
  },
  {
    id: 'sw.inventory',
    title: 'Installed package / program inventory',
    category: 'software',
    description: 'dpkg/rpm/Add-Remove Programs style inventory.',
    keywords: ['dpkg', 'rpm', 'winget', 'programs', 'packages'],
    platform: 'both',
    view: 'standard',
    runLabel: 'List packages',
  },
  {
    id: 'sw.prohibited',
    title: 'Prohibited software finder',
    category: 'software',
    description: 'Games, hacking tools, and unauthorized remote-admin kits.',
    keywords: ['nmap', 'wireshark', 'game', 'hack', 'prohibited'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Find prohibited',
  },
  {
    id: 'sw.updates',
    title: 'Update status',
    category: 'software',
    description: 'apt/yum/Windows Update read-only pending patch view.',
    keywords: ['apt', 'yum', 'dnf', 'wua', 'patches'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Check updates',
  },
  {
    id: 'sw.remote-access',
    title: 'Browser / remote access tool audit',
    category: 'software',
    description: 'Unexpected browsers, TeamViewer, AnyDesk, VNC, RDP extras.',
    keywords: ['teamviewer', 'anydesk', 'vnc', 'chrome', 'rdp'],
    platform: 'both',
    view: 'standard',
    runLabel: 'Audit RAT',
  },
  {
    id: 'win.registry',
    title: 'Registry harden checklist',
    category: 'windows',
    description: 'Common CyberPatriot keys: autoplay, LLMNR, guest, autorun.',
    keywords: ['reg', 'autoplay', 'llmnr', 'run key', 'smb1'],
    platform: 'windows',
    view: 'standard',
    runLabel: 'Check keys',
  },
  {
    id: 'win.secpol',
    title: 'Local Security Policy snapshot',
    category: 'windows',
    description: 'Account policy, audit policy, and user rights assignments.',
    keywords: ['secpol', 'secedit', 'user rights', 'audit policy'],
    platform: 'windows',
    view: 'standard',
    runLabel: 'Dump secpol',
  },
  {
    id: 'win.iis',
    title: 'IIS / feature inventory',
    category: 'windows',
    description: 'Installed Windows features, IIS sites, and dangerous modules.',
    keywords: ['iis', 'dism', 'optional features', 'asp'],
    platform: 'windows',
    view: 'standard',
    runLabel: 'Inventory IIS',
  },
  {
    id: 'win.powershell',
    title: 'PowerShell execution policy check',
    category: 'windows',
    description: 'Scope policies, transcription, and unconstrained language.',
    keywords: ['executionpolicy', 'unrestricted', 'transcription'],
    platform: 'windows',
    view: 'standard',
    runLabel: 'Check PS',
  },
  {
    id: 'linux.pam',
    title: 'PAM / login.defs audit',
    category: 'linux',
    description: 'pam_pwquality, faillock, umask, and encrypt method.',
    keywords: ['pam', 'login.defs', 'pwquality', 'faillock'],
    platform: 'linux',
    view: 'standard',
    runLabel: 'Audit PAM',
  },
  {
    id: 'linux.authorized-keys',
    title: 'SSH keys authorized_keys sweep',
    category: 'linux',
    description: 'Unexpected keys in user and root authorized_keys files.',
    keywords: ['authorized_keys', 'ssh-rsa', 'id_rsa'],
    platform: 'linux',
    view: 'standard',
    runLabel: 'Sweep keys',
  },
  {
    id: 'linux.modules',
    title: 'Kernel module / unused service sweep',
    category: 'linux',
    description: 'Loaded modules, uncommon filesystems, and leftover daemons.',
    keywords: ['lsmod', 'modprobe', 'usb-storage', 'dccp'],
    platform: 'linux',
    view: 'standard',
    runLabel: 'Sweep modules',
  },
  {
    id: 'linux.mac',
    title: 'AppArmor/SELinux status',
    category: 'linux',
    description: 'MAC layer enforcing/permissive/disabled and profile counts.',
    keywords: ['apparmor', 'selinux', 'getenforce', 'aa-status'],
    platform: 'linux',
    view: 'standard',
    runLabel: 'Check MAC',
  },
  {
    id: 'team.preflight',
    title: 'Pre-flight checklist',
    category: 'team',
    description: 'Scoreboard-oriented start-of-image checklist.',
    keywords: ['preflight', 'readme', 'forensics', 'snapshot', 'firewall'],
    platform: 'both',
    view: 'preflight',
    runLabel: 'Refresh',
  },
  {
    id: 'team.journal',
    title: 'Before/after change log',
    category: 'team',
    description: 'Session journal of every demo and mock action in this browser.',
    keywords: ['changelog', 'journal', 'undo', 'session'],
    platform: 'both',
    view: 'journal',
    runLabel: 'Refresh',
  },
  {
    id: 'team.export',
    title: 'Export findings JSON/CSV',
    category: 'team',
    description: 'Download current pane findings plus the session journal.',
    keywords: ['export', 'json', 'csv', 'report'],
    platform: 'both',
    view: 'export',
    runLabel: 'Build export',
  },
  {
    id: 'team.favorites',
    title: 'Op favorites / pin',
    category: 'team',
    description: 'Pinned operations for the heat of the round.',
    keywords: ['pin', 'star', 'favorites', 'bookmark'],
    platform: 'both',
    view: 'favorites',
    runLabel: 'Refresh',
  },
]

export const OPS_BY_ID: Record<string, OpDefinition> = Object.fromEntries(
  OPS.map((op) => [op.id, op]),
)

export function filterOps(query: string, ops: OpDefinition[] = OPS): OpDefinition[] {
  const q = query.trim().toLowerCase()
  if (!q) return ops
  return ops.filter((op) => {
    if (op.id.toLowerCase().includes(q)) return true
    if (op.title.toLowerCase().includes(q)) return true
    if (op.description.toLowerCase().includes(q)) return true
    if (op.category.toLowerCase().includes(q)) return true
    return op.keywords.some((k) => k.toLowerCase().includes(q))
  })
}
